INSERT INTO INSCRIPCION VALUES (,'17/12/1992',NULL,NULL,NULL,NULL);

INSERT INTO INSCRIPCION VALUES (,'11/07/2000',NULL,NULL,NULL,NULL);

INSERT INTO INSCRIPCION VALUES (,'02/01/1990',NULL,NULL,NULL,NULL);

INSERT INTO INSCRIPCION VALUES (,'21/06/1989',NULL,NULL,NULL,NULL);

INSERT INTO INSCRIPCION VALUES (,'04/04/1982',NULL,NULL,NULL,NULL);

INSERT INTO INSCRIPCION VALUES (,'19/05/2000',NULL,NULL,NULL,NULL);

INSERT INTO INSCRIPCION VALUES (,'21/11/1991',NULL,NULL,NULL,NULL);

INSERT INTO INSCRIPCION VALUES (,'12/08/1988',NULL,NULL,NULL,NULL);

/*Se deben agregar los ID de las personas, ya que para este momento
no se contaba con esa informacion */