/*===================================INSERTS MODULO 16====================================*/


/*-------------------------------COMPRA_CARRITO----------------------------*/

INSERT INTO COMPRA_CARRITO VALUES ('Tarjeta','2015-11-28','PAGADO',1);

INSERT INTO COMPRA_CARRITO VALUES ('Deposito','2016-11-28','PAGADO',2);

INSERT INTO COMPRA_CARRITO VALUES ('Transferencia','2015-11-28','PAGADO',3);

INSERT INTO COMPRA_CARRITO VALUES ('Tarjeta','2016-11-28','PAGADO',4);

INSERT INTO COMPRA_CARRITO VALUES ('Deposito','2015-11-28','PAGADO',5);

INSERT INTO COMPRA_CARRITO VALUES ('Transferencia','2016-11-28','PAGADO',6);

INSERT INTO COMPRA_CARRITO VALUES (NULL,NULL,'CARRITO',7);

INSERT INTO COMPRA_CARRITO VALUES (NULL,NULL,'CARRITO',8);

/*-------------------------------------------------------------------------*/

/*------------------------------DETALLE_COMPRA-----------------------------*/

INSERT INTO DETALLE_COMPRA VALUES (1,4500,4,NULL,NULL,1,NULL,NULL);

INSERT INTO DETALLE_COMPRA VALUES (1,3000,3,NULL,NULL,2,NULL,NULL);

INSERT INTO DETALLE_COMPRA VALUES (1,1200,2,NULL,NULL,4,NULL,NULL);

INSERT INTO DETALLE_COMPRA VALUES (1,5000,4,NULL,NULL,5,NULL,NULL);

INSERT INTO DETALLE_COMPRA VALUES (1,0,1,NULL,NULL,NULL,1,NULL);

INSERT INTO DETALLE_COMPRA VALUES (1,2000,1,NULL,NULL,NULL,2,NULL);

INSERT INTO DETALLE_COMPRA VALUES (7,1150,1,NULL,NULL,NULL,3,NULL);

INSERT INTO DETALLE_COMPRA VALUES (8,4500,5,NULL,NULL,3,NULL,NULL);

/*-------------------------------------------------------------------------*/


/*=======================================================================================*/