//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.Modulo8 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo8 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo8() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.Modulo8.RecursosBDModulo8", typeof(RecursosBDModulo8).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_Agregar_Restriccion_Cinta.
        /// </summary>
        internal static string AgregarRestriccionCinta {
            get {
                return ResourceManager.GetString("AgregarRestriccionCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_Consultar_Restriccion_Cinta.
        /// </summary>
        internal static string ConsultarRestriccionCinta {
            get {
                return ResourceManager.GetString("ConsultarRestriccionCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_Eliminar_Restriccion_Cinta.
        /// </summary>
        internal static string EliminarRestriccionCinta {
            get {
                return ResourceManager.GetString("EliminarRestriccionCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_Modificar_Restriccion_Cinta.
        /// </summary>
        internal static string ModificarRestriccionCinta {
            get {
                return ResourceManager.GetString("ModificarRestriccionCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CintaConsulta.
        /// </summary>
        internal static string ParamCinta {
            get {
                return ResourceManager.GetString("ParamCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Cinta.
        /// </summary>
        internal static string ParamCintaNueva {
            get {
                return ResourceManager.GetString("ParamCintaNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DescripcionRestriccionCinta.
        /// </summary>
        internal static string ParamDescripcionRestricionCinta {
            get {
                return ResourceManager.GetString("ParamDescripcionRestricionCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @HorasDocentes.
        /// </summary>
        internal static string ParamHorasDocentes {
            get {
                return ResourceManager.GetString("ParamHorasDocentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IdRestriccion.
        /// </summary>
        internal static string ParamIdRestriccion {
            get {
                return ResourceManager.GetString("ParamIdRestriccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PuntajeMinimo.
        /// </summary>
        internal static string ParamPuntosMinimos {
            get {
                return ResourceManager.GetString("ParamPuntosMinimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @TiempoMinimo.
        /// </summary>
        internal static string ParamTiempoMinimo {
            get {
                return ResourceManager.GetString("ParamTiempoMinimo", resourceCulture);
            }
        }
    }
}
