//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.Modulo8 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDRestriccionCompetencia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDRestriccionCompetencia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.Modulo8.RecursosBDRestriccionCompetencia", typeof(RecursosBDRestriccionCompetencia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_AgregarRestriccionCompetencia.
        /// </summary>
        internal static string AgregarRestriccionCompetencia {
            get {
                return ResourceManager.GetString("AgregarRestriccionCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcion.
        /// </summary>
        internal static string AliasDescripcion {
            get {
                return ResourceManager.GetString("AliasDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMax.
        /// </summary>
        internal static string AliasEdadMax {
            get {
                return ResourceManager.GetString("AliasEdadMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadMin.
        /// </summary>
        internal static string AliasEdadMin {
            get {
                return ResourceManager.GetString("AliasEdadMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaEdadMax.
        /// </summary>
        internal static string AliasFechaEdadMax {
            get {
                return ResourceManager.GetString("AliasFechaEdadMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaEdadMin.
        /// </summary>
        internal static string AliasFechaEdadMin {
            get {
                return ResourceManager.GetString("AliasFechaEdadMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCompetencia.
        /// </summary>
        internal static string AliasIdCompetencia {
            get {
                return ResourceManager.GetString("AliasIdCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCinta.
        /// </summary>
        internal static string AliasIdRcCinta {
            get {
                return ResourceManager.GetString("AliasIdRcCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string AliasIdRestriccionCompetencia {
            get {
                return ResourceManager.GetString("AliasIdRestriccionCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidad.
        /// </summary>
        internal static string AliasModalidad {
            get {
                return ResourceManager.GetString("AliasModalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sexo.
        /// </summary>
        internal static string AliasSexo {
            get {
                return ResourceManager.GetString("AliasSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_ConsultarRestriccionCompetencia.
        /// </summary>
        internal static string ConsultarTodasRestriccionCompetencia {
            get {
                return ResourceManager.GetString("ConsultarTodasRestriccionCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_EliminarRestriccionCompetencia.
        /// </summary>
        internal static string EliminarRestriccionCompetencia {
            get {
                return ResourceManager.GetString("EliminarRestriccionCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M8_ModificarRestriccionCompetencia.
        /// </summary>
        internal static string ModificarRestriccionCompetencia {
            get {
                return ResourceManager.GetString("ModificarRestriccionCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rest_comp_desc.
        /// </summary>
        internal static string ParamDescripcion {
            get {
                return ResourceManager.GetString("ParamDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rest_comp_edadmax.
        /// </summary>
        internal static string ParamEdadMax {
            get {
                return ResourceManager.GetString("ParamEdadMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rest_comp_edadmin.
        /// </summary>
        internal static string ParamEdadMin {
            get {
                return ResourceManager.GetString("ParamEdadMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ParamFechaEdadMax {
            get {
                return ResourceManager.GetString("ParamFechaEdadMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ParamFechaEdadMin {
            get {
                return ResourceManager.GetString("ParamFechaEdadMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cin_id.
        /// </summary>
        internal static string ParamIdCinta {
            get {
                return ResourceManager.GetString("ParamIdCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @com_id.
        /// </summary>
        internal static string ParamIdCompetencia {
            get {
                return ResourceManager.GetString("ParamIdCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @per_id.
        /// </summary>
        internal static string ParamIdPersona {
            get {
                return ResourceManager.GetString("ParamIdPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rest_comp_id.
        /// </summary>
        internal static string ParamIdRestriccionCompetencia {
            get {
                return ResourceManager.GetString("ParamIdRestriccionCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rest_comp_modalidad.
        /// </summary>
        internal static string ParamModalidad {
            get {
                return ResourceManager.GetString("ParamModalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @rest_comp_sexo.
        /// </summary>
        internal static string ParamSexo {
            get {
                return ResourceManager.GetString("ParamSexo", resourceCulture);
            }
        }
    }
}
