//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasUnitariasSKD.Modulo1 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosPU_Mod1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosPU_Mod1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PruebasUnitariasSKD.Modulo1.RecursosPU_Mod1", typeof(RecursosPU_Mod1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Magurno.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una descaripcion.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba-!&gt;.
        /// </summary>
        internal static string DescripcionInvalida {
            get {
                return ResourceManager.GetString("DescripcionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rafa91_1@hotmail.com.
        /// </summary>
        internal static string emailerrordoble {
            get {
                return ResourceManager.GetString("emailerrordoble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 13/11/1991.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        internal static string id2 {
            get {
                return ResourceManager.GetString("id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 15.
        /// </summary>
        internal static string Idrol {
            get {
                return ResourceManager.GetString("Idrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a carlo.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        internal static string nuevoRol {
            get {
                return ResourceManager.GetString("nuevoRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12345.
        /// </summary>
        internal static string PruebaCorrectoClave {
            get {
                return ResourceManager.GetString("PruebaCorrectoClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a perdomo21346@gmail.com.
        /// </summary>
        internal static string PruebaCorrectoResultado {
            get {
                return ResourceManager.GetString("PruebaCorrectoResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 12345.
        /// </summary>
        internal static string PruebaErrorClave {
            get {
                return ResourceManager.GetString("PruebaErrorClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error@gmail.com.
        /// </summary>
        internal static string pruebaErrorCorreo {
            get {
                return ResourceManager.GetString("pruebaErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hola.
        /// </summary>
        internal static string pruebaHash {
            get {
                return ResourceManager.GetString("pruebaHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hola.
        /// </summary>
        internal static string pruebaHash2 {
            get {
                return ResourceManager.GetString("pruebaHash2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a carloadmin.
        /// </summary>
        internal static string pruebainicioCorreo {
            get {
                return ResourceManager.GetString("pruebainicioCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5ae2bacffebdf3e8e37decdd343ac728.
        /// </summary>
        internal static string PruebaRestablecerClave {
            get {
                return ResourceManager.GetString("PruebaRestablecerClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        internal static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        internal static string Rol1 {
            get {
                return ResourceManager.GetString("Rol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin Sistema.
        /// </summary>
        internal static string Rol2 {
            get {
                return ResourceManager.GetString("Rol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organización.
        /// </summary>
        internal static string Rol3 {
            get {
                return ResourceManager.GetString("Rol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin Organización.
        /// </summary>
        internal static string Rol4 {
            get {
                return ResourceManager.GetString("Rol4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dojo.
        /// </summary>
        internal static string Rol5 {
            get {
                return ResourceManager.GetString("Rol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin Dojo.
        /// </summary>
        internal static string Rol6 {
            get {
                return ResourceManager.GetString("Rol6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrenador.
        /// </summary>
        internal static string Rol7 {
            get {
                return ResourceManager.GetString("Rol7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atleta.
        /// </summary>
        internal static string Rol8 {
            get {
                return ResourceManager.GetString("Rol8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Representante.
        /// </summary>
        internal static string Rol9 {
            get {
                return ResourceManager.GetString("Rol9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dmin.
        /// </summary>
        internal static string RolInvalido {
            get {
                return ResourceManager.GetString("RolInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a carloadmin.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Vacio {
            get {
                return ResourceManager.GetString("Vacio", resourceCulture);
            }
        }
    }
}
