//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasUnitariasSKD.Modulo1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosPU_Mod1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosPU_Mod1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PruebasUnitariasSKD.Modulo1.RecursosPU_Mod1", typeof(RecursosPU_Mod1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12345.
        /// </summary>
        internal static string PruebaCorrectoClave {
            get {
                return ResourceManager.GetString("PruebaCorrectoClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@gmail.com.
        /// </summary>
        internal static string pruebaCorrectoCorreo {
            get {
                return ResourceManager.GetString("pruebaCorrectoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@gmail.com.
        /// </summary>
        internal static string PruebaCorrectoResultado {
            get {
                return ResourceManager.GetString("PruebaCorrectoResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12345.
        /// </summary>
        internal static string PruebaErrorClave {
            get {
                return ResourceManager.GetString("PruebaErrorClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error@gmail.com.
        /// </summary>
        internal static string pruebaErrorCorreo {
            get {
                return ResourceManager.GetString("pruebaErrorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hola.
        /// </summary>
        internal static string pruebaHash {
            get {
                return ResourceManager.GetString("pruebaHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hola.
        /// </summary>
        internal static string pruebaHash2 {
            get {
                return ResourceManager.GetString("pruebaHash2", resourceCulture);
            }
        }
    }
}
