//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace templateApp.GUI.Master {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosInterfazMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosInterfazMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("templateApp.GUI.Master.RecursosInterfazMaster", typeof(RecursosInterfazMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://.
        /// </summary>
        internal static string AliasHttp {
            get {
                return ResourceManager.GetString("AliasHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/GUI/Master/Inicio.aspx.
        /// </summary>
        internal static string direccionMaster_Inicio {
            get {
                return ResourceManager.GetString("direccionMaster_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/GUI/Master/menuLateral.xml.
        /// </summary>
        internal static string direccionMaster_MenuLateral {
            get {
                return ResourceManager.GetString("direccionMaster_MenuLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/GUI/Master/menuSuperior.xml.
        /// </summary>
        internal static string direccionMaster_MenuSuperior {
            get {
                return ResourceManager.GetString("direccionMaster_MenuSuperior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleta.
        /// </summary>
        internal static string rolAtleta {
            get {
                return ResourceManager.GetString("rolAtleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleta(Menor).
        /// </summary>
        internal static string rolAtletaMenor {
            get {
                return ResourceManager.GetString("rolAtletaMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dojo.
        /// </summary>
        internal static string rolDojo {
            get {
                return ResourceManager.GetString("rolDojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacion.
        /// </summary>
        internal static string rolOrganizacion {
            get {
                return ResourceManager.GetString("rolOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representante.
        /// </summary>
        internal static string rolRepresentante {
            get {
                return ResourceManager.GetString("rolRepresentante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        internal static string rolSistema {
            get {
                return ResourceManager.GetString("rolSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imagen.
        /// </summary>
        internal static string sessionImagen {
            get {
                return ResourceManager.GetString("sessionImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        internal static string sessionLogout {
            get {
                return ResourceManager.GetString("sessionLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rol.
        /// </summary>
        internal static string sessionRol {
            get {
                return ResourceManager.GetString("sessionRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roles.
        /// </summary>
        internal static string sessionRoles {
            get {
                return ResourceManager.GetString("sessionRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuarioID.
        /// </summary>
        internal static string sessionUsuarioID {
            get {
                return ResourceManager.GetString("sessionUsuarioID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string sessionUsuarioNombre {
            get {
                return ResourceManager.GetString("sessionUsuarioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string splitRoles {
            get {
                return ResourceManager.GetString("splitRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string tagId {
            get {
                return ResourceManager.GetString("tagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        internal static string tagLink {
            get {
                return ResourceManager.GetString("tagLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.
        /// </summary>
        internal static string tagName {
            get {
                return ResourceManager.GetString("tagName", resourceCulture);
            }
        }
    }
}
