//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.Modulo16 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo16 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo16() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.Modulo16.RecursosBDModulo16", typeof(RecursosBDModulo16).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_CONSULTAREVENTOS.
        /// </summary>
        internal static string CONSULTAR_EVENTOS {
            get {
                return ResourceManager.GetString("CONSULTAR_EVENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_CONSULTARINVENTARIO.
        /// </summary>
        internal static string CONSULTAR_IMPLEMENTOS {
            get {
                return ResourceManager.GetString("CONSULTAR_IMPLEMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M16_DETALLARIMPLEMENTO.
        /// </summary>
        internal static string DETALLAR_IMPLEMENTO {
            get {
                return ResourceManager.GetString("DETALLAR_IMPLEMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impColor.
        /// </summary>
        internal static string PARAMETRO_COLOR {
            get {
                return ResourceManager.GetString("PARAMETRO_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impDescripcion.
        /// </summary>
        internal static string PARAMETRO_DESCRIPCION {
            get {
                return ResourceManager.GetString("PARAMETRO_DESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impEstatus.
        /// </summary>
        internal static string PARAMETRO_ESTATUS {
            get {
                return ResourceManager.GetString("PARAMETRO_ESTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idEvento.
        /// </summary>
        internal static string PARAMETRO_IDEVENTO {
            get {
                return ResourceManager.GetString("PARAMETRO_IDEVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idImplemento.
        /// </summary>
        internal static string PARAMETRO_IDIMPLEMENTO {
            get {
                return ResourceManager.GetString("PARAMETRO_IDIMPLEMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impImagen.
        /// </summary>
        internal static string PARAMETRO_IMAGEN {
            get {
                return ResourceManager.GetString("PARAMETRO_IMAGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @iditem.
        /// </summary>
        internal static string PARAMETRO_ITEM {
            get {
                return ResourceManager.GetString("PARAMETRO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impMarca.
        /// </summary>
        internal static string PARAMETRO_MARCA {
            get {
                return ResourceManager.GetString("PARAMETRO_MARCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impNombre.
        /// </summary>
        internal static string PARAMETRO_NOMBRE {
            get {
                return ResourceManager.GetString("PARAMETRO_NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impPrecio.
        /// </summary>
        internal static string PARAMETRO_PRECIO {
            get {
                return ResourceManager.GetString("PARAMETRO_PRECIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impTalla.
        /// </summary>
        internal static string PARAMETRO_TALLA {
            get {
                return ResourceManager.GetString("PARAMETRO_TALLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to impTipo.
        /// </summary>
        internal static string PARAMETRO_TIPO {
            get {
                return ResourceManager.GetString("PARAMETRO_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tipoitem.
        /// </summary>
        internal static string PARAMETRO_TIPO_ITEM {
            get {
                return ResourceManager.GetString("PARAMETRO_TIPO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idusuario.
        /// </summary>
        internal static string PARAMETRO_USUARIO {
            get {
                return ResourceManager.GetString("PARAMETRO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINAR_ITEM.
        /// </summary>
        internal static string PROCEDIMIENTO_ELIMINAR_ITEM {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_ELIMINAR_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRAR_PAGO.
        /// </summary>
        internal static string PROCEDIMIENTO_REGISTRAR_PAGO {
            get {
                return ResourceManager.GetString("PROCEDIMIENTO_REGISTRAR_PAGO", resourceCulture);
            }
        }
    }
}
