//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaNegociosSKD.Modulo1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursosLogicaModulo1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosLogicaModulo1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicaNegociosSKD.Modulo1.RecursosLogicaModulo1", typeof(RecursosLogicaModulo1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm0123456789 ..
        /// </summary>
        public static string abc {
            get {
                return ResourceManager.GetString("abc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm0123456789-_..
        /// </summary>
        public static string abc_ {
            get {
                return ResourceManager.GetString("abc_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA-KARATEDO:Reestablecer contraseña.
        /// </summary>
        public static string asuntoSAKARATEDO {
            get {
                return ResourceManager.GetString("asuntoSAKARATEDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_00_10.
        /// </summary>
        public static string Codigo_Error_Hash {
            get {
                return ResourceManager.GetString("Codigo_Error_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_00_11.
        /// </summary>
        public static string Codigo_Error_InicioSesion {
            get {
                return ResourceManager.GetString("Codigo_Error_InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to karate1234.
        /// </summary>
        public static string cuentaClaveSAKARATEDO {
            get {
                return ResourceManager.GetString("cuentaClaveSAKARATEDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sakaratedo@gmail.com.
        /// </summary>
        public static string cuentaCorreoSAKARATEDO {
            get {
                return ResourceManager.GetString("cuentaCorreoSAKARATEDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /GUI/Modulo1/RestablecerContrasena.aspx.
        /// </summary>
        public static string direccionM1_RestablecerContraseña {
            get {
                return ResourceManager.GetString("direccionM1_RestablecerContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encontrado aqui:.
        /// </summary>
        public static string errorGenerico {
            get {
                return ResourceManager.GetString("errorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        public static string hostSAKARATEDO {
            get {
                return ResourceManager.GetString("hostSAKARATEDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;.
        /// </summary>
        public static string lineBreak {
            get {
                return ResourceManager.GetString("lineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:.
        /// </summary>
        public static string localhost {
            get {
                return ResourceManager.GetString("localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo no se encuentra registrado en sistema.
        /// </summary>
        public static string Mensaje_Error_CorreoNoRegistrado {
            get {
                return ResourceManager.GetString("Mensaje_Error_CorreoNoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encontrado en login.hash.
        /// </summary>
        public static string Mensaje_Error_Hash {
            get {
                return ResourceManager.GetString("Mensaje_Error_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encontrado en login.iniciarSesion.
        /// </summary>
        public static string Mensaje_Error_InicioSesion {
            get {
                return ResourceManager.GetString("Mensaje_Error_InicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no posee permiso para ingresar al sistema, comuníquese con un administrador de SAKARATEDO..
        /// </summary>
        public static string Mensaje_Error_Roles {
            get {
                return ResourceManager.GetString("Mensaje_Error_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje:.
        /// </summary>
        public static string mensajeGenerico {
            get {
                return ResourceManager.GetString("mensajeGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimado usuario, se ha solicitado desde la plataforma de SA-KARATEDO el reestablecimiento de la contraseña asociada a su cuenta, si usted no produjo dicha solicitud omitir la importancia del correo, de lo contrario deberá seguir los pasas que a continuacion se le presenta para poder reestablecer su contraseña:&lt;br&gt;
        ///           Diríjase al siguiente enlace en el cual podrá asignar una nueva contraseña a su cuenta de SA-KARATEDO.&lt;/br&gt;&lt;br&gt;&lt;/br&gt;.
        /// </summary>
        public static string mensajeSAKARATEDO {
            get {
                return ResourceManager.GetString("mensajeSAKARATEDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string parametroURLId {
            get {
                return ResourceManager.GetString("parametroURLId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        public static string puertoEnvioSAKARATEDO {
            get {
                return ResourceManager.GetString("puertoEnvioSAKARATEDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23072.
        /// </summary>
        public static string puertoSAKARATEDO {
            get {
                return ResourceManager.GetString("puertoSAKARATEDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleta.
        /// </summary>
        public static string rolAtleta {
            get {
                return ResourceManager.GetString("rolAtleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleta(Menor).
        /// </summary>
        public static string rolAtletaMenor {
            get {
                return ResourceManager.GetString("rolAtletaMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dojo.
        /// </summary>
        public static string rolDojo {
            get {
                return ResourceManager.GetString("rolDojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizacion.
        /// </summary>
        public static string rolOrganizacion {
            get {
                return ResourceManager.GetString("rolOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representante.
        /// </summary>
        public static string rolRepresentante {
            get {
                return ResourceManager.GetString("rolRepresentante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string rolSistema {
            get {
                return ResourceManager.GetString("rolSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/br&gt;.
        /// </summary>
        public static string slashLineBreak {
            get {
                return ResourceManager.GetString("slashLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string splitRoles {
            get {
                return ResourceManager.GetString("splitRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fecha.
        /// </summary>
        public static string variableFecha {
            get {
                return ResourceManager.GetString("variableFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;fecha=.
        /// </summary>
        public static string variableFechaHTTP {
            get {
                return ResourceManager.GetString("variableFechaHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restablecer.
        /// </summary>
        public static string variableRestablecer {
            get {
                return ResourceManager.GetString("variableRestablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?restablecer=.
        /// </summary>
        public static string variableRestablecerHTTP {
            get {
                return ResourceManager.GetString("variableRestablecerHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiempo.
        /// </summary>
        public static string variableTiempo {
            get {
                return ResourceManager.GetString("variableTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;hora=.
        /// </summary>
        public static string variableTiempoHTTP {
            get {
                return ResourceManager.GetString("variableTiempoHTTP", resourceCulture);
            }
        }
    }
}
