//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.DAO.Modulo3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosDaoModulo3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosDaoModulo3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.DAO.Modulo3.RecursosDaoModulo3", typeof(RecursosDaoModulo3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3_AgregarOrganizacion.
        /// </summary>
        internal static string AgregarOrganizacion {
            get {
                return ResourceManager.GetString("AgregarOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direccionOrganizacion.
        /// </summary>
        internal static string AliasDireccionOrg {
            get {
                return ResourceManager.GetString("AliasDireccionOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emailOrganiacion.
        /// </summary>
        internal static string AliasEmailOrg {
            get {
                return ResourceManager.GetString("AliasEmailOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estadoOrganizacion.
        /// </summary>
        internal static string AliasEstadoOrg {
            get {
                return ResourceManager.GetString("AliasEstadoOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idOrganizacion.
        /// </summary>
        internal static string AliasIdOrg {
            get {
                return ResourceManager.GetString("AliasIdOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreEstilo.
        /// </summary>
        internal static string AliasNombreEstilo {
            get {
                return ResourceManager.GetString("AliasNombreEstilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreOrganizacion.
        /// </summary>
        internal static string AliasNombreOrg {
            get {
                return ResourceManager.GetString("AliasNombreOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telefonoOrganiacion.
        /// </summary>
        internal static string AliasTelefonoOrg {
            get {
                return ResourceManager.GetString("AliasTelefonoOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3_BuscarEstilo.
        /// </summary>
        internal static string BuscarEstilo {
            get {
                return ResourceManager.GetString("BuscarEstilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3_BuscarNombreOrganizacion.
        /// </summary>
        internal static string BuscarNombreOrganizacion {
            get {
                return ResourceManager.GetString("BuscarNombreOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_001.
        /// </summary>
        internal static string Codigo_Error_Formato {
            get {
                return ResourceManager.GetString("Codigo_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_003.
        /// </summary>
        internal static string Codigo_Estilo_Inexistente {
            get {
                return ResourceManager.GetString("Codigo_Estilo_Inexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_002.
        /// </summary>
        internal static string Codigo_Organizacion_Existente {
            get {
                return ResourceManager.GetString("Codigo_Organizacion_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3_ConsultarComboOrganizacion.
        /// </summary>
        internal static string ConsultarComboORG {
            get {
                return ResourceManager.GetString("ConsultarComboORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3_ConsultarOrganizacion.
        /// </summary>
        internal static string ConsultarOrganizacion {
            get {
                return ResourceManager.GetString("ConsultarOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3_ConsultarOrganizacionXId.
        /// </summary>
        internal static string ConsultarOrganizacionXId {
            get {
                return ResourceManager.GetString("ConsultarOrganizacionXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3_EliminarOrganizacion.
        /// </summary>
        internal static string EliminarOrganizacion {
            get {
                return ResourceManager.GetString("EliminarOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de parseo.
        /// </summary>
        internal static string Mensaje_Error_Formato {
            get {
                return ResourceManager.GetString("Mensaje_Error_Formato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Tecnica seleccionada no existe.
        /// </summary>
        internal static string Mensaje_Estilo_Inexistente {
            get {
                return ResourceManager.GetString("Mensaje_Estilo_Inexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Organizacion ya existe.
        /// </summary>
        internal static string Mensaje_Organizacion_Existente {
            get {
                return ResourceManager.GetString("Mensaje_Organizacion_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida del Método.
        /// </summary>
        internal static string MensajeFinInfoLogger {
            get {
                return ResourceManager.GetString("MensajeFinInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioInfoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3_ModificarOrganizacion.
        /// </summary>
        internal static string ModificarOrganizacion {
            get {
                return ResourceManager.GetString("ModificarOrganizacion", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to M3_ModificarStatusOrganizacion.
        /// </summary>
        internal static string ModificarStatusOrganizacion
        {
            get
            {
                return ResourceManager.GetString("ModificarStatusOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @emailOrganizacion.
        /// </summary>
        internal static string ParamEmailOrg {
            get {
                return ResourceManager.GetString("ParamEmailOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombreEstado.
        /// </summary>
        internal static string ParamEstadoOrg {
            get {
                return ResourceManager.GetString("ParamEstadoOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombreEstilo.
        /// </summary>
        internal static string ParamEstiloOrg {
            get {
                return ResourceManager.GetString("ParamEstiloOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @id_organizacion.
        /// </summary>
        internal static string ParamIdEliminarOrg {
            get {
                return ResourceManager.GetString("ParamIdEliminarOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idOrganizacion.
        /// </summary>
        internal static string ParamIdOrg {
            get {
                return ResourceManager.GetString("ParamIdOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombreDireccion.
        /// </summary>
        internal static string ParamNombreDirOrg {
            get {
                return ResourceManager.GetString("ParamNombreDirOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombreOrganizacion.
        /// </summary>
        internal static string ParamNombreOrg {
            get {
                return ResourceManager.GetString("ParamNombreOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @numEstilo.
        /// </summary>
        internal static string ParamSalidaNumEstilo {
            get {
                return ResourceManager.GetString("ParamSalidaNumEstilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @numOrganizacion.
        /// </summary>
        internal static string ParamSalidaNumOrganizacion {
            get {
                return ResourceManager.GetString("ParamSalidaNumOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @telefOrganizacion.
        /// </summary>
        internal static string ParamTelOrg {
            get {
                return ResourceManager.GetString("ParamTelOrg", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to estatus
        /// </summary>
        internal static string AliasStatusOrg
        {
            get
            {
                return ResourceManager.GetString("AliasStatusOrg", resourceCulture);
            }
        }

    }
}
