//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.Modulo11 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo11 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo11() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.Modulo11.RecursosBDModulo11", typeof(RecursosBDModulo11).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apellidoPersona.
        /// </summary>
        internal static string aliasApellidoPersona {
            get {
                return ResourceManager.GetString("aliasApellidoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobado.
        /// </summary>
        internal static string aliasAprobado {
            get {
                return ResourceManager.GetString("aliasAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cintaFinal.
        /// </summary>
        internal static string aliasCintaFinal {
            get {
                return ResourceManager.GetString("aliasCintaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cintaInicial.
        /// </summary>
        internal static string aliasCintaInicial {
            get {
                return ResourceManager.GetString("aliasCintaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadFinal.
        /// </summary>
        internal static string aliasEdadFinal {
            get {
                return ResourceManager.GetString("aliasEdadFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edadInicial.
        /// </summary>
        internal static string aliasEdadInicial {
            get {
                return ResourceManager.GetString("aliasEdadInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to especialidadCompetencia.
        /// </summary>
        internal static string aliasEspecialidadCompetencia {
            get {
                return ResourceManager.GetString("aliasEspecialidadCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaInicioCompetencia.
        /// </summary>
        internal static string aliasFechaCompetencia {
            get {
                return ResourceManager.GetString("aliasFechaCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaInicioEvento.
        /// </summary>
        internal static string aliasFechaEvento {
            get {
                return ResourceManager.GetString("aliasFechaEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCategoria.
        /// </summary>
        internal static string aliasIdCategoria {
            get {
                return ResourceManager.GetString("aliasIdCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCompetencia.
        /// </summary>
        internal static string aliasIdCompetencia {
            get {
                return ResourceManager.GetString("aliasIdCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idEvento.
        /// </summary>
        internal static string aliasIdEvento {
            get {
                return ResourceManager.GetString("aliasIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idInscripcion.
        /// </summary>
        internal static string aliasIdInscripcion {
            get {
                return ResourceManager.GetString("aliasIdInscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idPersona.
        /// </summary>
        internal static string aliasIdPersona {
            get {
                return ResourceManager.GetString("aliasIdPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idResultado.
        /// </summary>
        internal static string aliasIdResultado {
            get {
                return ResourceManager.GetString("aliasIdResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreCompetencia.
        /// </summary>
        internal static string aliasNombreCompetencia {
            get {
                return ResourceManager.GetString("aliasNombreCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreEvento.
        /// </summary>
        internal static string aliasNombreEvento {
            get {
                return ResourceManager.GetString("aliasNombreEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombrePersona.
        /// </summary>
        internal static string aliasNombrePersona {
            get {
                return ResourceManager.GetString("aliasNombrePersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sexoCategoria.
        /// </summary>
        internal static string aliasSexoCategoria {
            get {
                return ResourceManager.GetString("aliasSexoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tipoEvento.
        /// </summary>
        internal static string aliasTipoEvento {
            get {
                return ResourceManager.GetString("aliasTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_aprobado.
        /// </summary>
        internal static string ParametroAprobadoResultadoAscenso {
            get {
                return ResourceManager.GetString("ParametroAprobadoResultadoAscenso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_idCategoria.
        /// </summary>
        internal static string ParametroIdCategoria {
            get {
                return ResourceManager.GetString("ParametroIdCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_idCompetencia.
        /// </summary>
        internal static string ParametroIdCompetencia {
            get {
                return ResourceManager.GetString("ParametroIdCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_idEspecialidad.
        /// </summary>
        internal static string ParametroIdEspecialidad {
            get {
                return ResourceManager.GetString("ParametroIdEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_idEvento.
        /// </summary>
        internal static string ParametroIdEvento {
            get {
                return ResourceManager.GetString("ParametroIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_idInscripcion.
        /// </summary>
        internal static string ParametroIdInscripcion {
            get {
                return ResourceManager.GetString("ParametroIdInscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_atleta1.
        /// </summary>
        internal static string ParametroResultadoAtleta1 {
            get {
                return ResourceManager.GetString("ParametroResultadoAtleta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_atleta2.
        /// </summary>
        internal static string ParametroResultadoAtleta2 {
            get {
                return ResourceManager.GetString("ParametroResultadoAtleta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_idInscripcion1.
        /// </summary>
        internal static string ParametroResultadoInscripcion1 {
            get {
                return ResourceManager.GetString("ParametroResultadoInscripcion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_idInscripcion2.
        /// </summary>
        internal static string ParametroResultadoInscripcion2 {
            get {
                return ResourceManager.GetString("ParametroResultadoInscripcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_jurado1.
        /// </summary>
        internal static string ParametroResultadoJurado1 {
            get {
                return ResourceManager.GetString("ParametroResultadoJurado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_jurado2.
        /// </summary>
        internal static string ParametroResultadoJurado2 {
            get {
                return ResourceManager.GetString("ParametroResultadoJurado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @_jurado3.
        /// </summary>
        internal static string ParametroResultadoJurado3 {
            get {
                return ResourceManager.GetString("ParametroResultadoJurado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_CategoriasCompetenciaEspecialidad.
        /// </summary>
        internal static string ProcedimientoCategoriasCompetenciaEspecialidad {
            get {
                return ResourceManager.GetString("ProcedimientoCategoriasCompetenciaEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_CategoriasResultadoAscensos.
        /// </summary>
        internal static string ProcedimientoCategoriasResultadoAscensos {
            get {
                return ResourceManager.GetString("ProcedimientoCategoriasResultadoAscensos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_ConsultarResultadoPasadoC.
        /// </summary>
        internal static string ProcedimientoConsultarResultadoPasadoC {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarResultadoPasadoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_ConsultarResultadoPasadoE.
        /// </summary>
        internal static string ProcedimientoConsultarResultadoPasadoE {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarResultadoPasadoE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_EspecialidadesEnUnaCompetencia.
        /// </summary>
        internal static string ProcedimientoEspecialidadesEnUnaCompetencia {
            get {
                return ResourceManager.GetString("ProcedimientoEspecialidadesEnUnaCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_ModificarAscenso.
        /// </summary>
        internal static string ProcedimientoModificarExamenAscenso {
            get {
                return ResourceManager.GetString("ProcedimientoModificarExamenAscenso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_ModificarKata.
        /// </summary>
        internal static string ProcedimientoModificarKata {
            get {
                return ResourceManager.GetString("ProcedimientoModificarKata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_ModificarKumite.
        /// </summary>
        internal static string ProcedimientoModificarKumite {
            get {
                return ResourceManager.GetString("ProcedimientoModificarKumite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_PersonasParticipanCompetencia.
        /// </summary>
        internal static string ProcedimientoPersonasCompitenCompetencia {
            get {
                return ResourceManager.GetString("ProcedimientoPersonasCompitenCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11_PersonasEnCategoriaYAscenso.
        /// </summary>
        internal static string ProcedimientoPersonasEnCategoriaAscenso {
            get {
                return ResourceManager.GetString("ProcedimientoPersonasEnCategoriaAscenso", resourceCulture);
            }
        }
    }
}
