//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.Modulo14 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo14 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo14() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.Modulo14.RecursosBDModulo14", typeof(RecursosBDModulo14).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dis_contenido.
        /// </summary>
        internal static string AtributocontenidoDiseño {
            get {
                return ResourceManager.GetString("AtributocontenidoDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dis_contenido.
        /// </summary>
        internal static string AtributocontenidoDiseño1 {
            get {
                return ResourceManager.GetString("AtributocontenidoDiseño1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dat_id.
        /// </summary>
        internal static string AtributoIdDato {
            get {
                return ResourceManager.GetString("AtributoIdDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dis_id.
        /// </summary>
        internal static string AtributoIdDiseño {
            get {
                return ResourceManager.GetString("AtributoIdDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dis_id.
        /// </summary>
        internal static string AtributoIdDiseño1 {
            get {
                return ResourceManager.GetString("AtributoIdDiseño1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pla_id.
        /// </summary>
        internal static string AtributoIdPlanilla {
            get {
                return ResourceManager.GetString("AtributoIdPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANILLA_pla_id.
        /// </summary>
        internal static string AtributoIdPlanillaDatos {
            get {
                return ResourceManager.GetString("AtributoIdPlanillaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tip_id.
        /// </summary>
        internal static string AtributoIdTipoPlanilla {
            get {
                return ResourceManager.GetString("AtributoIdTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tip_id.
        /// </summary>
        internal static string AtributoIdTipoPlanilla1 {
            get {
                return ResourceManager.GetString("AtributoIdTipoPlanilla1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dat_nombre.
        /// </summary>
        internal static string AtributoNombre_Dato {
            get {
                return ResourceManager.GetString("AtributoNombre_Dato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pla_nombre.
        /// </summary>
        internal static string AtributoNombrePlanilla {
            get {
                return ResourceManager.GetString("AtributoNombrePlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tip_nombre.
        /// </summary>
        internal static string AtributoNombreTipoPlanilla {
            get {
                return ResourceManager.GetString("AtributoNombreTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tip_nombre.
        /// </summary>
        internal static string AtributoNombreTipoPlanilla1 {
            get {
                return ResourceManager.GetString("AtributoNombreTipoPlanilla1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pla_status.
        /// </summary>
        internal static string AtributoStatusPlanilla {
            get {
                return ResourceManager.GetString("AtributoStatusPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @dis_contenido.
        /// </summary>
        internal static string ParametroContenido {
            get {
                return ResourceManager.GetString("ParametroContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @dis_contenido.
        /// </summary>
        internal static string ParametroContenido1 {
            get {
                return ResourceManager.GetString("ParametroContenido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PLANILLA_pla_id.
        /// </summary>
        internal static string ParametroDiseñoPlanilla {
            get {
                return ResourceManager.GetString("ParametroDiseñoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PLANILLA_pla_id.
        /// </summary>
        internal static string ParametroDiseñoPlanilla1 {
            get {
                return ResourceManager.GetString("ParametroDiseñoPlanilla1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @dis_id.
        /// </summary>
        internal static string ParametroID {
            get {
                return ResourceManager.GetString("ParametroID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @DATO_dat_id.
        /// </summary>
        internal static string ParametroIdDatos {
            get {
                return ResourceManager.GetString("ParametroIdDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pla_id.
        /// </summary>
        internal static string ParametroIdPlanilla {
            get {
                return ResourceManager.GetString("ParametroIdPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tip_id.
        /// </summary>
        internal static string ParametroIdTipoPlanilla {
            get {
                return ResourceManager.GetString("ParametroIdTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @dat_nombre.
        /// </summary>
        internal static string ParametroNombreDato {
            get {
                return ResourceManager.GetString("ParametroNombreDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pla_nombre.
        /// </summary>
        internal static string ParametroNombrePlanilla {
            get {
                return ResourceManager.GetString("ParametroNombrePlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PLANILLA_pla_id.
        /// </summary>
        internal static string ParametroPlanilla {
            get {
                return ResourceManager.GetString("ParametroPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PLANILLA_pla_id.
        /// </summary>
        internal static string ParametroPlanilla1 {
            get {
                return ResourceManager.GetString("ParametroPlanilla1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @pla_status.
        /// </summary>
        internal static string ParametroSatusPlanilla {
            get {
                return ResourceManager.GetString("ParametroSatusPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @tip_nombre.
        /// </summary>
        internal static string ParametroTipoPlanilla {
            get {
                return ResourceManager.GetString("ParametroTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @TIPO_PLANILLA_tip_id.
        /// </summary>
        internal static string ParametroTipoPlanillaFK {
            get {
                return ResourceManager.GetString("ParametroTipoPlanillaFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ProcedureAgregarTipoPlanilla.
        /// </summary>
        internal static string ProcedimientoAgregarTipoPlanilla {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_Procedure_IdTipoPlanilla.
        /// </summary>
        internal static string ProcedimientoObtenerIdTipoPlanilla {
            get {
                return ResourceManager.GetString("ProcedimientoObtenerIdTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ProcedureAgregarDatoPlanilla.
        /// </summary>
        internal static string ProcedureAgregarDatoPlanilla {
            get {
                return ResourceManager.GetString("ProcedureAgregarDatoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ProcedureAgregarDatoPlanillaID.
        /// </summary>
        internal static string ProcedureAgregarDatoPlanillaID {
            get {
                return ResourceManager.GetString("ProcedureAgregarDatoPlanillaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ProcedureAgregarPlanilla.
        /// </summary>
        internal static string ProcedureAgregarPlanilla {
            get {
                return ResourceManager.GetString("ProcedureAgregarPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ProcedureConsultarDatosPlanillaID.
        /// </summary>
        internal static string ProcedureConsultarDatosPlanillaId {
            get {
                return ResourceManager.GetString("ProcedureConsultarDatosPlanillaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ConsultarDiseño.
        /// </summary>
        internal static string ProcedureConsultarDiseño {
            get {
                return ResourceManager.GetString("ProcedureConsultarDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ConsultarDiseño.
        /// </summary>
        internal static string ProcedureConsultarDiseño1 {
            get {
                return ResourceManager.GetString("ProcedureConsultarDiseño1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_Procedure_ListarDatos.
        /// </summary>
        internal static string ProcedureConsultarListaDatos {
            get {
                return ResourceManager.GetString("ProcedureConsultarListaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ConsultarPlanillasCreadas.
        /// </summary>
        internal static string ProcedureConsultarPlanillasCreadas {
            get {
                return ResourceManager.GetString("ProcedureConsultarPlanillasCreadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ProcedureConsultarPlanillaID.
        /// </summary>
        internal static string ProcedureConsultatPlanillaID {
            get {
                return ResourceManager.GetString("ProcedureConsultatPlanillaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ProcedureEliminarDatosPlanilla.
        /// </summary>
        internal static string ProcedureEliminarDatosPlanilla {
            get {
                return ResourceManager.GetString("ProcedureEliminarDatosPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_AgregarDiseño.
        /// </summary>
        internal static string ProcedureGuardarDiseño {
            get {
                return ResourceManager.GetString("ProcedureGuardarDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_AgregarDiseño.
        /// </summary>
        internal static string ProcedureGuardarDiseño1 {
            get {
                return ResourceManager.GetString("ProcedureGuardarDiseño1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_Procedure_ListarTipoPlanilla.
        /// </summary>
        internal static string ProcedureListaTipoPlanilla {
            get {
                return ResourceManager.GetString("ProcedureListaTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ModificarDiseño.
        /// </summary>
        internal static string ProcedureModificarDiseño {
            get {
                return ResourceManager.GetString("ProcedureModificarDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M14_ProcedureModificarPlanilla.
        /// </summary>
        internal static string ProcedureModificarPlanilla {
            get {
                return ResourceManager.GetString("ProcedureModificarPlanilla", resourceCulture);
            }
        }
    }
}
