//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.Modulo14 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo14 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo14() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.Modulo14.RecursosBDModulo14", typeof(RecursosBDModulo14).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PERSONA_per_id.
        /// </summary>
        internal static string AtriburoPersonaId {
            get {
                return ResourceManager.GetString("AtriburoPersonaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a comp_nombre.
        /// </summary>
        internal static string AtributoCompetenciaNombre {
            get {
                return ResourceManager.GetString("AtributoCompetenciaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dis_contenido.
        /// </summary>
        internal static string AtributocontenidoDiseño {
            get {
                return ResourceManager.GetString("AtributocontenidoDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eve_nombre.
        /// </summary>
        internal static string AtributoEventoNombre {
            get {
                return ResourceManager.GetString("AtributoEventoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sol_pla_fecha_creacion.
        /// </summary>
        internal static string AtributoFechaCreacion {
            get {
                return ResourceManager.GetString("AtributoFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sol_pla_fecha_reincorporacion.
        /// </summary>
        internal static string AtributoFechaReincorporacion {
            get {
                return ResourceManager.GetString("AtributoFechaReincorporacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sol_pla_fecha_retiro.
        /// </summary>
        internal static string AtributoFechaRetiro {
            get {
                return ResourceManager.GetString("AtributoFechaRetiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dat_id.
        /// </summary>
        internal static string AtributoIdDato {
            get {
                return ResourceManager.GetString("AtributoIdDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dis_id.
        /// </summary>
        internal static string AtributoIdDiseño {
            get {
                return ResourceManager.GetString("AtributoIdDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pla_id.
        /// </summary>
        internal static string AtributoIdPlanilla {
            get {
                return ResourceManager.GetString("AtributoIdPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLANILLA_pla_id.
        /// </summary>
        internal static string AtributoIdPlanillaDatos {
            get {
                return ResourceManager.GetString("AtributoIdPlanillaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sol_pla_id.
        /// </summary>
        internal static string AtributoIdSolicitud {
            get {
                return ResourceManager.GetString("AtributoIdSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tip_id.
        /// </summary>
        internal static string AtributoIdTipoPlanilla {
            get {
                return ResourceManager.GetString("AtributoIdTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSCRIPCION_ins_id.
        /// </summary>
        internal static string AtributoInscripcion {
            get {
                return ResourceManager.GetString("AtributoInscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sol_pla_motivo.
        /// </summary>
        internal static string AtributoMotivo {
            get {
                return ResourceManager.GetString("AtributoMotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dat_nombre.
        /// </summary>
        internal static string AtributoNombre_Dato {
            get {
                return ResourceManager.GetString("AtributoNombre_Dato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pla_nombre.
        /// </summary>
        internal static string AtributoNombrePlanilla {
            get {
                return ResourceManager.GetString("AtributoNombrePlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tip_nombre.
        /// </summary>
        internal static string AtributoNombreTipoPlanilla {
            get {
                return ResourceManager.GetString("AtributoNombreTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pla_status.
        /// </summary>
        internal static string AtributoStatusPlanilla {
            get {
                return ResourceManager.GetString("AtributoStatusPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tipo.
        /// </summary>
        internal static string AtributoTipo {
            get {
                return ResourceManager.GetString("AtributoTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @dis_contenido.
        /// </summary>
        internal static string ParametroContenido {
            get {
                return ResourceManager.GetString("ParametroContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @PLANILLA_pla_id.
        /// </summary>
        internal static string ParametroDiseñoPlanilla {
            get {
                return ResourceManager.GetString("ParametroDiseñoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @dis_id.
        /// </summary>
        internal static string ParametroID {
            get {
                return ResourceManager.GetString("ParametroID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @DATO_dat_id.
        /// </summary>
        internal static string ParametroIdDatos {
            get {
                return ResourceManager.GetString("ParametroIdDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pla_id.
        /// </summary>
        internal static string ParametroIdPlanilla {
            get {
                return ResourceManager.GetString("ParametroIdPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @tip_id.
        /// </summary>
        internal static string ParametroIdTipoPlanilla {
            get {
                return ResourceManager.GetString("ParametroIdTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @dat_nombre.
        /// </summary>
        internal static string ParametroNombreDato {
            get {
                return ResourceManager.GetString("ParametroNombreDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pla_nombre.
        /// </summary>
        internal static string ParametroNombrePlanilla {
            get {
                return ResourceManager.GetString("ParametroNombrePlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @PERSONA_per_id.
        /// </summary>
        internal static string ParametroPersonaPerId {
            get {
                return ResourceManager.GetString("ParametroPersonaPerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @PLANILLA_pla_id.
        /// </summary>
        internal static string ParametroPlanilla {
            get {
                return ResourceManager.GetString("ParametroPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pla_status.
        /// </summary>
        internal static string ParametroSatusPlanilla {
            get {
                return ResourceManager.GetString("ParametroSatusPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @tip_nombre.
        /// </summary>
        internal static string ParametroTipoPlanilla {
            get {
                return ResourceManager.GetString("ParametroTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @TIPO_PLANILLA_tip_id.
        /// </summary>
        internal static string ParametroTipoPlanillaFK {
            get {
                return ResourceManager.GetString("ParametroTipoPlanillaFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ProcedureAgregarTipoPlanilla.
        /// </summary>
        internal static string ProcedimientoAgregarTipoPlanilla {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_Procedure_IdTipoPlanilla.
        /// </summary>
        internal static string ProcedimientoObtenerIdTipoPlanilla {
            get {
                return ResourceManager.GetString("ProcedimientoObtenerIdTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ProcedureAgregarDatoPlanilla.
        /// </summary>
        internal static string ProcedureAgregarDatoPlanilla {
            get {
                return ResourceManager.GetString("ProcedureAgregarDatoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ProcedureAgregarDatoPlanillaID.
        /// </summary>
        internal static string ProcedureAgregarDatoPlanillaID {
            get {
                return ResourceManager.GetString("ProcedureAgregarDatoPlanillaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ProcedureAgregarPlanilla.
        /// </summary>
        internal static string ProcedureAgregarPlanilla {
            get {
                return ResourceManager.GetString("ProcedureAgregarPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_CambioDeStatusPlanilla.
        /// </summary>
        internal static string ProcedureCambiarStatusPlanilla {
            get {
                return ResourceManager.GetString("ProcedureCambiarStatusPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ProcedureConsultarDatosPlanillaID.
        /// </summary>
        internal static string ProcedureConsultarDatosPlanillaId {
            get {
                return ResourceManager.GetString("ProcedureConsultarDatosPlanillaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ConsultarDiseño.
        /// </summary>
        internal static string ProcedureConsultarDiseño {
            get {
                return ResourceManager.GetString("ProcedureConsultarDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_Procedure_ListarDatos.
        /// </summary>
        internal static string ProcedureConsultarListaDatos {
            get {
                return ResourceManager.GetString("ProcedureConsultarListaDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ConsultarPlanillasCreadas.
        /// </summary>
        internal static string ProcedureConsultarPlanillasCreadas {
            get {
                return ResourceManager.GetString("ProcedureConsultarPlanillasCreadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ConsultarSolicitudPlanilla.
        /// </summary>
        internal static string ProcedureConsultarSolicitudPlanilla {
            get {
                return ResourceManager.GetString("ProcedureConsultarSolicitudPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ProcedureConsultarPlanillaID.
        /// </summary>
        internal static string ProcedureConsultatPlanillaID {
            get {
                return ResourceManager.GetString("ProcedureConsultatPlanillaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ProcedureEliminarDatosPlanilla.
        /// </summary>
        internal static string ProcedureEliminarDatosPlanilla {
            get {
                return ResourceManager.GetString("ProcedureEliminarDatosPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_AgregarDiseño.
        /// </summary>
        internal static string ProcedureGuardarDiseño {
            get {
                return ResourceManager.GetString("ProcedureGuardarDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_Procedure_ListarTipoPlanilla.
        /// </summary>
        internal static string ProcedureListaTipoPlanilla {
            get {
                return ResourceManager.GetString("ProcedureListaTipoPlanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ModificarDiseño.
        /// </summary>
        internal static string ProcedureModificarDiseño {
            get {
                return ResourceManager.GetString("ProcedureModificarDiseño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M14_ProcedureModificarPlanilla.
        /// </summary>
        internal static string ProcedureModificarPlanilla {
            get {
                return ResourceManager.GetString("ProcedureModificarPlanilla", resourceCulture);
            }
        }
    }
}
