//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaNegociosSKD.Modulo16 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosLogicaModulo16 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosLogicaModulo16() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicaNegociosSKD.Modulo16.RecursosLogicaModulo16", typeof(RecursosLogicaModulo16).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_01.
        /// </summary>
        internal static string CODIGO_EXCEPCION_GENERICO {
            get {
                return ResourceManager.GetString("CODIGO_EXCEPCION_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_05.
        /// </summary>
        internal static string Codigo_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_03.
        /// </summary>
        internal static string Codigo_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_05.
        /// </summary>
        internal static string Codigo_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_04.
        /// </summary>
        internal static string Codigo_ExcepcionParametro {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_16_02.
        /// </summary>
        internal static string Codigo_ExcepcionSql {
            get {
                return ResourceManager.GetString("Codigo_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uno de los parametros no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje__ExcepcionParametro {
            get {
                return ResourceManager.GetString("Mensaje__ExcepcionParametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresando al metodo.
        /// </summary>
        internal static string MENSAJE_ENTRADA_LOGGER {
            get {
                return ResourceManager.GetString("MENSAJE_ENTRADA_LOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado en la capa de datos.
        /// </summary>
        internal static string MENSAJE_EXCEPCION_GENERICO {
            get {
                return ResourceManager.GetString("MENSAJE_EXCEPCION_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uno de los atributos no existe en el procedimiento ejecutado.
        /// </summary>
        internal static string Mensaje_ExcepcionAtributo {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error se ha producido una excepcion.
        /// </summary>
        internal static string Mensaje_ExcepcionGeneral {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error existe una referencia nula.
        /// </summary>
        internal static string Mensaje_ExcepcionNullReference {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error existe un conflicto con la conexión a la base de datos.
        /// </summary>
        internal static string Mensaje_ExcepcionSql {
            get {
                return ResourceManager.GetString("Mensaje_ExcepcionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saliendo del metodo.
        /// </summary>
        internal static string MENSAJE_SALIDA_LOGGER {
            get {
                return ResourceManager.GetString("MENSAJE_SALIDA_LOGGER", resourceCulture);
            }
        }
    }
}
