//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace templateApp.GUI.Modulo11 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M11_RecursoInterfaz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M11_RecursoInterfaz() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("templateApp.GUI.Modulo11.M11_RecursoInterfaz", typeof(M11_RecursoInterfaz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td&gt;.
        /// </summary>
        internal static string AbrirTD {
            get {
                return ResourceManager.GetString("AbrirTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;nombre1&quot;&gt;.
        /// </summary>
        internal static string AbrirTDNombre1 {
            get {
                return ResourceManager.GetString("AbrirTDNombre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td class=&quot;nombre2&quot;&gt;.
        /// </summary>
        internal static string AbrirTDNombre2 {
            get {
                return ResourceManager.GetString("AbrirTDNombre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;.
        /// </summary>
        internal static string AbrirTR {
            get {
                return ResourceManager.GetString("AbrirTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a class.
        /// </summary>
        internal static string alertClase {
            get {
                return ResourceManager.GetString("alertClase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a role.
        /// </summary>
        internal static string alertRole {
            get {
                return ResourceManager.GetString("alertRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobado.
        /// </summary>
        internal static string Aprobado {
            get {
                return ResourceManager.GetString("Aprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BotonCerrar {
            get {
                return ResourceManager.GetString("BotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot;  href=&quot;M11_DetalleResultadoCompetencia.aspx?tipo=Competencia&amp;mostrar=.
        /// </summary>
        internal static string BotonInfoCompetencia {
            get {
                return ResourceManager.GetString("BotonInfoCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot;  href=&quot;M11_DetalleResultadoCompetencia.aspx?tipo=Evento&amp;mostrar=.
        /// </summary>
        internal static string BotonInfoEvento {
            get {
                return ResourceManager.GetString("BotonInfoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-default glyphicon glyphicon-pencil&quot; href=&quot;M11_ModificarResultadoCompetencia.aspx?tipo=Competencia&amp;modificar=.
        /// </summary>
        internal static string BotonModificarCompetencia {
            get {
                return ResourceManager.GetString("BotonModificarCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-default glyphicon glyphicon-pencil&quot; href=&quot;M11_ModificarResultadoCompetencia.aspx?tipo=Evento&amp;modificar=.
        /// </summary>
        internal static string BotonModificarEvento {
            get {
                return ResourceManager.GetString("BotonModificarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_categoria.
        /// </summary>
        internal static string CategoriaEvento {
            get {
                return ResourceManager.GetString("CategoriaEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/td&gt;.
        /// </summary>
        internal static string CerrarTD {
            get {
                return ResourceManager.GetString("CerrarTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/tr&gt;.
        /// </summary>
        internal static string CerrarTR {
            get {
                return ResourceManager.GetString("CerrarTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competencia.
        /// </summary>
        internal static string Competencia {
            get {
                return ResourceManager.GetString("Competencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        internal static string especialidadAmbos {
            get {
                return ResourceManager.GetString("especialidadAmbos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_especialidad.
        /// </summary>
        internal static string EspecialidadEvento {
            get {
                return ResourceManager.GetString("EspecialidadEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string especialidadKata {
            get {
                return ResourceManager.GetString("especialidadKata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        internal static string especialidadKumite {
            get {
                return ResourceManager.GetString("especialidadKumite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evento.
        /// </summary>
        internal static string Evento {
            get {
                return ResourceManager.GetString("Evento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_fecha.
        /// </summary>
        internal static string FechaEvento {
            get {
                return ResourceManager.GetString("FechaEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_IdEvento.
        /// </summary>
        internal static string IdEvento {
            get {
                return ResourceManager.GetString("IdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kata .
        /// </summary>
        internal static string Kata {
            get {
                return ResourceManager.GetString("Kata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kata y Kumite.
        /// </summary>
        internal static string Kata_Kumite {
            get {
                return ResourceManager.GetString("Kata_Kumite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kumite.
        /// </summary>
        internal static string Kumite {
            get {
                return ResourceManager.GetString("Kumite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a modificar.
        /// </summary>
        internal static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mostrar.
        /// </summary>
        internal static string Mostrar {
            get {
                return ResourceManager.GetString("Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Aprobado.
        /// </summary>
        internal static string NoAprobado {
            get {
                return ResourceManager.GetString("NoAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option selected value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo1 {
            get {
                return ResourceManager.GetString("r1Combo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option selected value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo10 {
            get {
                return ResourceManager.GetString("r1Combo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option selected value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo2 {
            get {
                return ResourceManager.GetString("r1Combo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option selected value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo3 {
            get {
                return ResourceManager.GetString("r1Combo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option selected value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo4 {
            get {
                return ResourceManager.GetString("r1Combo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option selected value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo5 {
            get {
                return ResourceManager.GetString("r1Combo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option selected value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo6 {
            get {
                return ResourceManager.GetString("r1Combo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option selected value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo7 {
            get {
                return ResourceManager.GetString("r1Combo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option selected value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo8 {
            get {
                return ResourceManager.GetString("r1Combo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option selected value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r1Combo9 {
            get {
                return ResourceManager.GetString("r1Combo9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option selected value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo1 {
            get {
                return ResourceManager.GetString("r2Combo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option selected value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo10 {
            get {
                return ResourceManager.GetString("r2Combo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option selected value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo2 {
            get {
                return ResourceManager.GetString("r2Combo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option selected value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo3 {
            get {
                return ResourceManager.GetString("r2Combo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option selected value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo4 {
            get {
                return ResourceManager.GetString("r2Combo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option selected value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo5 {
            get {
                return ResourceManager.GetString("r2Combo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option selected value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo6 {
            get {
                return ResourceManager.GetString("r2Combo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option selected value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo7 {
            get {
                return ResourceManager.GetString("r2Combo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option selected value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo8 {
            get {
                return ResourceManager.GetString("r2Combo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option selected value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r2Combo9 {
            get {
                return ResourceManager.GetString("r2Combo9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option selected value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo1 {
            get {
                return ResourceManager.GetString("r3Combo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option selected value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo10 {
            get {
                return ResourceManager.GetString("r3Combo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option selected value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo2 {
            get {
                return ResourceManager.GetString("r3Combo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option selected value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo3 {
            get {
                return ResourceManager.GetString("r3Combo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option selected value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo4 {
            get {
                return ResourceManager.GetString("r3Combo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option selected value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo5 {
            get {
                return ResourceManager.GetString("r3Combo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option selected value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo6 {
            get {
                return ResourceManager.GetString("r3Combo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option selected value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo7 {
            get {
                return ResourceManager.GetString("r3Combo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option selected value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo8 {
            get {
                return ResourceManager.GetString("r3Combo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:30%&quot;&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;option value=&quot;8&quot;&gt;8&lt;/option&gt;
        ///            &lt;option selected value=&quot;9&quot;&gt;9&lt;/option&gt;
        ///            &lt;option value=&quot;10&quot;&gt;10&lt;/option&gt;
        ///        &lt;/select&gt;.
        /// </summary>
        internal static string r3Combo9 {
            get {
                return ResourceManager.GetString("r3Combo9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_Rango.
        /// </summary>
        internal static string RangoEvento {
            get {
                return ResourceManager.GetString("RangoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=16.
        /// </summary>
        internal static string ResultadoAmbosAgregarError {
            get {
                return ResourceManager.GetString("ResultadoAmbosAgregarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=15.
        /// </summary>
        internal static string ResultadoAmbosAgregarExito {
            get {
                return ResourceManager.GetString("ResultadoAmbosAgregarExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=10.
        /// </summary>
        internal static string ResultadoAmbosModificadoError {
            get {
                return ResourceManager.GetString("ResultadoAmbosModificadoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=9.
        /// </summary>
        internal static string ResultadoAmbosModificadoExito {
            get {
                return ResourceManager.GetString("ResultadoAmbosModificadoExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=3.
        /// </summary>
        internal static string ResultadoAscensoAgregarError {
            get {
                return ResourceManager.GetString("ResultadoAscensoAgregarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=1.
        /// </summary>
        internal static string ResultadoAscensoAgregarExito {
            get {
                return ResourceManager.GetString("ResultadoAscensoAgregarExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=6.
        /// </summary>
        internal static string ResultadoKataAgregarError {
            get {
                return ResourceManager.GetString("ResultadoKataAgregarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=5.
        /// </summary>
        internal static string ResultadoKataAgregarExito {
            get {
                return ResourceManager.GetString("ResultadoKataAgregarExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=6.
        /// </summary>
        internal static string ResultadoKataModificadoError {
            get {
                return ResourceManager.GetString("ResultadoKataModificadoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=5.
        /// </summary>
        internal static string ResultadoKataModificadoExito {
            get {
                return ResourceManager.GetString("ResultadoKataModificadoExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=14.
        /// </summary>
        internal static string ResultadoKumiteAgregarError {
            get {
                return ResourceManager.GetString("ResultadoKumiteAgregarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=13.
        /// </summary>
        internal static string ResultadoKumiteAgregarExito {
            get {
                return ResourceManager.GetString("ResultadoKumiteAgregarExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=8.
        /// </summary>
        internal static string ResultadoKumiteModificadoError {
            get {
                return ResourceManager.GetString("ResultadoKumiteModificadoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=7.
        /// </summary>
        internal static string ResultadoKumiteModificadoExito {
            get {
                return ResourceManager.GetString("ResultadoKumiteModificadoExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=4.
        /// </summary>
        internal static string ResultadoModificadoError {
            get {
                return ResourceManager.GetString("ResultadoModificadoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_ListarResultadoCompetencia.aspx?success=2.
        /// </summary>
        internal static string ResultadoModificadoExito {
            get {
                return ResourceManager.GetString("ResultadoModificadoExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo&quot; class=&quot;form-control&quot; style=&quot;width:25%&quot;&gt;
        ///                            &lt;option selected value=&quot;Seleccionar&quot;&gt;Seleccionar:&lt;/option&gt;
        ///                            &lt;option value=&quot;Aprobado&quot;&gt;Aprobado&lt;/option&gt;
        ///                            &lt;option value=&quot;No Aprobado&quot;&gt;No Aprobado&lt;/option&gt;
        ///                        &lt;/select&gt;.
        /// </summary>
        internal static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Categoria:.
        /// </summary>
        internal static string SeleccionarCategoria {
            get {
                return ResourceManager.GetString("SeleccionarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo1&quot; class=&quot;form-control&quot; style=&quot;width:45%&quot;&gt;                                                                                    &lt;option selected value=&quot;Seleccionar&quot;&gt;Seleccionar:&lt;/option&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;op [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SeleccionarCombo1 {
            get {
                return ResourceManager.GetString("SeleccionarCombo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo2&quot; class=&quot;form-control&quot; style=&quot;width:45%&quot;&gt;                                                                                    &lt;option selected value=&quot;Seleccionar&quot;&gt;Seleccionar:&lt;/option&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;op [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SeleccionarCombo2 {
            get {
                return ResourceManager.GetString("SeleccionarCombo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo3&quot; class=&quot;form-control&quot; style=&quot;width:45%&quot;&gt;                                                                                    &lt;option selected value=&quot;Seleccionar&quot;&gt;Seleccionar:&lt;/option&gt;
        ///            &lt;option value=&quot;1&quot;&gt;1&lt;/option&gt;
        ///            &lt;option value=&quot;2&quot;&gt;2&lt;/option&gt;
        ///            &lt;option value=&quot;3&quot;&gt;3&lt;/option&gt;
        ///            &lt;option value=&quot;4&quot;&gt;4&lt;/option&gt;
        ///            &lt;option value=&quot;5&quot;&gt;5&lt;/option&gt;
        ///            &lt;option value=&quot;6&quot;&gt;6&lt;/option&gt;
        ///            &lt;option value=&quot;7&quot;&gt;7&lt;/option&gt;
        ///            &lt;op [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SeleccionarCombo3 {
            get {
                return ResourceManager.GetString("SeleccionarCombo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Especialidad:.
        /// </summary>
        internal static string SeleccionarEspecialidad {
            get {
                return ResourceManager.GetString("SeleccionarEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Evento:.
        /// </summary>
        internal static string SeleccionarEvento {
            get {
                return ResourceManager.GetString("SeleccionarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo&quot; class=&quot;form-control&quot; style=&quot;width:25%&quot;&gt;
        ///      &lt;option selected value=&quot;Aprobado&quot;&gt;Aprobado&lt;/option&gt;
        ///      &lt;option value=&quot;No Aprobado&quot;&gt;No Aprobado&lt;/option&gt;
        ///    &lt;/select&gt;.
        /// </summary>
        internal static string selectAprobado {
            get {
                return ResourceManager.GetString("selectAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;select id=&quot;combo&quot; class=&quot;form-control&quot; style=&quot;width:25%&quot;&gt;
        ///      &lt;option value=&quot;Aprobado&quot;&gt;Aprobado&lt;/option&gt;
        ///      &lt;option selected value=&quot;No Aprobado&quot;&gt;No Aprobado&lt;/option&gt;
        ///    &lt;/select&gt;.
        /// </summary>
        internal static string selectNoAprobado {
            get {
                return ResourceManager.GetString("selectNoAprobado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tipo.
        /// </summary>
        internal static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M11_tipo.
        /// </summary>
        internal static string TipoEvento {
            get {
                return ResourceManager.GetString("TipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N.
        /// </summary>
        internal static string valorNo {
            get {
                return ResourceManager.GetString("valorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S.
        /// </summary>
        internal static string valorSi {
            get {
                return ResourceManager.GetString("valorSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
