//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaNegociosSKD.Modulo2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursosLogicaModulo2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosLogicaModulo2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicaNegociosSKD.Modulo2.RecursosLogicaModulo2", typeof(RecursosLogicaModulo2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaKARAteDO2015.
        /// </summary>
        public static string claveDES {
            get {
                return ResourceManager.GetString("claveDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_00_13.
        /// </summary>
        public static string Codigo_Error_AgregarRol {
            get {
                return ResourceManager.GetString("Codigo_Error_AgregarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_00_14.
        /// </summary>
        public static string Codigo_Error_ConsultarRolUsuario {
            get {
                return ResourceManager.GetString("Codigo_Error_ConsultarRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_00_12.
        /// </summary>
        public static string Codigo_Error_EliminarRol {
            get {
                return ResourceManager.GetString("Codigo_Error_EliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_00_15.
        /// </summary>
        public static string Codigo_Error_FiltrarRol {
            get {
                return ResourceManager.GetString("Codigo_Error_FiltrarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_00_10.
        /// </summary>
        public static string Codigo_Error_Hash {
            get {
                return ResourceManager.GetString("Codigo_Error_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_17.
        /// </summary>
        public static string Codigo_Error_RolNoEditable {
            get {
                return ResourceManager.GetString("Codigo_Error_RolNoEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_00_16.
        /// </summary>
        public static string Codigo_Error_ValidarPrioridad {
            get {
                return ResourceManager.GetString("Codigo_Error_ValidarPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x2.
        /// </summary>
        public static string equis2 {
            get {
                return ResourceManager.GetString("equis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;asp:DropDownList id=&quot;RolList&quot; class=&quot;btn btn-default dropdown-toggle&quot; AutoPostBack=&quot;True&quot; OnSelectedIndexChanged=&quot;Selection_Change&quot; runat=&quot;server&quot;&gt;.
        /// </summary>
        public static string etiquetaAperturaDropDawn {
            get {
                return ResourceManager.GetString("etiquetaAperturaDropDawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/asp:DropDownList&gt;.
        /// </summary>
        public static string etiquetaCierreDropDawn {
            get {
                return ResourceManager.GetString("etiquetaCierreDropDawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar rol.
        /// </summary>
        public static string Mensaje_Error_AgregarRol {
            get {
                return ResourceManager.GetString("Mensaje_Error_AgregarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al consultar rol de usuario.
        /// </summary>
        public static string Mensaje_Error_ConsultarRolUsuario {
            get {
                return ResourceManager.GetString("Mensaje_Error_ConsultarRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar rol .
        /// </summary>
        public static string Mensaje_Error_EliminarRol {
            get {
                return ResourceManager.GetString("Mensaje_Error_EliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al filtrar rol.
        /// </summary>
        public static string Mensaje_Error_FiltarRol {
            get {
                return ResourceManager.GetString("Mensaje_Error_FiltarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encontrado en login.hash.
        /// </summary>
        public static string Mensaje_Error_Hash {
            get {
                return ResourceManager.GetString("Mensaje_Error_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error rol no editable.
        /// </summary>
        public static string Mensaje_Error_RolNoEditable {
            get {
                return ResourceManager.GetString("Mensaje_Error_RolNoEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol no registrado/validado en sistema: LogicaNegociosSKD.logicaRol.prioridadRol().
        /// </summary>
        public static string Mensaje_Error_RolSinRegistro {
            get {
                return ResourceManager.GetString("Mensaje_Error_RolSinRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al validar prioridad.
        /// </summary>
        public static string Mensaje_Error_ValidarPrioridad {
            get {
                return ResourceManager.GetString("Mensaje_Error_ValidarPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string signoMas {
            get {
                return ResourceManager.GetString("signoMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;asp:ListItem Value=&quot;.
        /// </summary>
        public static string subEtiquetaApertura {
            get {
                return ResourceManager.GetString("subEtiquetaApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&gt;.
        /// </summary>
        public static string subEtiquetaCierreApertura {
            get {
                return ResourceManager.GetString("subEtiquetaCierreApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/asp:ListItem&gt;.
        /// </summary>
        public static string subEtiquetaCierreTotal {
            get {
                return ResourceManager.GetString("subEtiquetaCierreTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;asp:ListItem Selected=&quot;True&quot; Value=&quot;select&quot;&gt;-Seleccionar rol- &lt;/asp:ListItem&gt;.
        /// </summary>
        public static string subEtiquetaSeleccionar {
            get {
                return ResourceManager.GetString("subEtiquetaSeleccionar", resourceCulture);
            }
        }
    }
}
