//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.DAO.Modulo9 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosDaoEvento {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosDaoEvento() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.DAO.Modulo9.RecursosDaoEvento", typeof(RecursosDaoEvento).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costoEvento.
        /// </summary>
        internal static string AliasCostoEvento {
            get {
                return ResourceManager.GetString("AliasCostoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripcionEvento.
        /// </summary>
        internal static string AliasDescripcionEvento {
            get {
                return ResourceManager.GetString("AliasDescripcionEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estadoEvento.
        /// </summary>
        internal static string AliasEstadoEvento {
            get {
                return ResourceManager.GetString("AliasEstadoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaFin.
        /// </summary>
        internal static string AliasFechaFin {
            get {
                return ResourceManager.GetString("AliasFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fechaInicio.
        /// </summary>
        internal static string AliasFechaInicio {
            get {
                return ResourceManager.GetString("AliasFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horaFin.
        /// </summary>
        internal static string AliasHoraFin {
            get {
                return ResourceManager.GetString("AliasHoraFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to horaInicio.
        /// </summary>
        internal static string AliasHoraInicio {
            get {
                return ResourceManager.GetString("AliasHoraInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idEvento.
        /// </summary>
        internal static string AliasIdEvento {
            get {
                return ResourceManager.GetString("AliasIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idTipo.
        /// </summary>
        internal static string AliasIDTipoEvento {
            get {
                return ResourceManager.GetString("AliasIDTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreEvento.
        /// </summary>
        internal static string AliasNombreEvento {
            get {
                return ResourceManager.GetString("AliasNombreEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tipoEvento.
        /// </summary>
        internal static string AliasTipoEvento {
            get {
                return ResourceManager.GetString("AliasTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKD_00_004.
        /// </summary>
        internal static string CodigoErrorFormato {
            get {
                return ResourceManager.GetString("CodigoErrorFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de parseo.
        /// </summary>
        internal static string MensajeErrorFormato {
            get {
                return ResourceManager.GetString("MensajeErrorFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida del Método.
        /// </summary>
        internal static string MensajeFinInfoLogger {
            get {
                return ResourceManager.GetString("MensajeFinInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioInfoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @costo.
        /// </summary>
        internal static string ParametroCostoEvento {
            get {
                return ResourceManager.GetString("ParametroCostoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @descripcion.
        /// </summary>
        internal static string ParametroDescripcionEvento {
            get {
                return ResourceManager.GetString("ParametroDescripcionEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @estado.
        /// </summary>
        internal static string ParametroEstadoEvento {
            get {
                return ResourceManager.GetString("ParametroEstadoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fechaFin.
        /// </summary>
        internal static string ParametroFechaFin {
            get {
                return ResourceManager.GetString("ParametroFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @fechaInicio.
        /// </summary>
        internal static string ParametroFechaInicio {
            get {
                return ResourceManager.GetString("ParametroFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @horaFin.
        /// </summary>
        internal static string ParametroHoraFin {
            get {
                return ResourceManager.GetString("ParametroHoraFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @horaInicio.
        /// </summary>
        internal static string ParametroHoraInicio {
            get {
                return ResourceManager.GetString("ParametroHoraInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idCategoria.
        /// </summary>
        internal static string ParametroIdCategoria {
            get {
                return ResourceManager.GetString("ParametroIdCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idEvento.
        /// </summary>
        internal static string ParametroIdEvento {
            get {
                return ResourceManager.GetString("ParametroIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idPersona.
        /// </summary>
        internal static string ParametroIdPersona {
            get {
                return ResourceManager.GetString("ParametroIdPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idTipoEvento.
        /// </summary>
        internal static string ParametroIdTipoEvento {
            get {
                return ResourceManager.GetString("ParametroIdTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idUbicacion.
        /// </summary>
        internal static string ParametroIdUbicacion {
            get {
                return ResourceManager.GetString("ParametroIdUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombre.
        /// </summary>
        internal static string ParametroNombreEvento {
            get {
                return ResourceManager.GetString("ParametroNombreEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @nombreTipoEvento.
        /// </summary>
        internal static string ParametroNombreTipoEvento {
            get {
                return ResourceManager.GetString("ParametroNombreTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_ConsultarEventoXID.
        /// </summary>
        internal static string ProcedimentoConsultarEventoXID {
            get {
                return ResourceManager.GetString("ProcedimentoConsultarEventoXID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_AgregarEventoCompleto.
        /// </summary>
        internal static string ProcedimientoAgregarEvento {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_AgregarEventoConTipo.
        /// </summary>
        internal static string ProcedimientoAgregarEventoConTipo {
            get {
                return ResourceManager.GetString("ProcedimientoAgregarEventoConTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_ConsultarAscensosRangoFecha.
        /// </summary>
        internal static string ProcedimientoConsultarAscensosRangoFecha {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarAscensosRangoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_ConsultarEventos.
        /// </summary>
        internal static string ProcedimientoConsultarEventos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_ConsultarEventosRangoFecha.
        /// </summary>
        internal static string ProcedimientoConsultarEventosRangoFecha {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarEventosRangoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_TodasLasFechasAscensos.
        /// </summary>
        internal static string ProcedimientoConsultarFechasAscensos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarFechasAscensos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_TodasLasFechas.
        /// </summary>
        internal static string ProcedimientoConsultarHorarios {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_ConsultarTipoEventos.
        /// </summary>
        internal static string ProcedimientoConsultarTiposEventos {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarTiposEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_ModificarEvento.
        /// </summary>
        internal static string ProcedimientoModificarEvento {
            get {
                return ResourceManager.GetString("ProcedimientoModificarEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M9_ModificarEventoConTipo.
        /// </summary>
        internal static string ProcedimientoModificarEventoConTipo {
            get {
                return ResourceManager.GetString("ProcedimientoModificarEventoConTipo", resourceCulture);
            }
        }
    }
}
