//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.Modulo7 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo7 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo7() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.Modulo7.RecursosBDModulo7", typeof(RecursosBDModulo7).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasCategoriaEventoId {
            get {
                return ResourceManager.GetString("AliasCategoriaEventoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clasificacion.
        /// </summary>
        internal static string AliasCintaClasificacion {
            get {
                return ResourceManager.GetString("AliasCintaClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fecha.
        /// </summary>
        internal static string AliasCintaFecha {
            get {
                return ResourceManager.GetString("AliasCintaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string AliasCintaNombre {
            get {
                return ResourceManager.GetString("AliasCintaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a orden.
        /// </summary>
        internal static string AliasCintaOrden {
            get {
                return ResourceManager.GetString("AliasCintaOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rango.
        /// </summary>
        internal static string AliasCintaRango {
            get {
                return ResourceManager.GetString("AliasCintaRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a significado.
        /// </summary>
        internal static string AliasCintaSignificado {
            get {
                return ResourceManager.GetString("AliasCintaSignificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        internal static string AliasCiudad {
            get {
                return ResourceManager.GetString("AliasCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idCategoria.
        /// </summary>
        internal static string AliasCompetenciaCategoriaId {
            get {
                return ResourceManager.GetString("AliasCompetenciaCategoriaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a costo.
        /// </summary>
        internal static string AliasCompetenciaCosto {
            get {
                return ResourceManager.GetString("AliasCompetenciaCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaFin.
        /// </summary>
        internal static string AliasCompetenciaFechaFin {
            get {
                return ResourceManager.GetString("AliasCompetenciaFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaInicio.
        /// </summary>
        internal static string AliasCompetenciaFechaInicio {
            get {
                return ResourceManager.GetString("AliasCompetenciaFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kata.
        /// </summary>
        internal static string AliasCompetenciaKata {
            get {
                return ResourceManager.GetString("AliasCompetenciaKata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kata y Kumite.
        /// </summary>
        internal static string AliasCompetenciaKataKumite {
            get {
                return ResourceManager.GetString("AliasCompetenciaKataKumite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kumite.
        /// </summary>
        internal static string AliasCompetenciaKumite {
            get {
                return ResourceManager.GetString("AliasCompetenciaKumite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string AliasCompetenciaNombre {
            get {
                return ResourceManager.GetString("AliasCompetenciaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a status.
        /// </summary>
        internal static string AliasCompetenciaStatus {
            get {
                return ResourceManager.GetString("AliasCompetenciaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tipo.
        /// </summary>
        internal static string AliasCompetenciaTipo {
            get {
                return ResourceManager.GetString("AliasCompetenciaTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idUbicacion.
        /// </summary>
        internal static string AliasCompetenciaUbicacionId {
            get {
                return ResourceManager.GetString("AliasCompetenciaUbicacionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a costo.
        /// </summary>
        internal static string AliasCostoEvento {
            get {
                return ResourceManager.GetString("AliasCostoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a descripcion.
        /// </summary>
        internal static string AliasDescripcionEvento {
            get {
                return ResourceManager.GetString("AliasDescripcionEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a direccion.
        /// </summary>
        internal static string AliasDireccion {
            get {
                return ResourceManager.GetString("AliasDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a email.
        /// </summary>
        internal static string AliasDojoEmail {
            get {
                return ResourceManager.GetString("AliasDojoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasDojoEventoId {
            get {
                return ResourceManager.GetString("AliasDojoEventoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasDojoId {
            get {
                return ResourceManager.GetString("AliasDojoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string AliasDojoNombre {
            get {
                return ResourceManager.GetString("AliasDojoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a organizacion.
        /// </summary>
        internal static string AliasDojoOrganizacionId {
            get {
                return ResourceManager.GetString("AliasDojoOrganizacionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a telefono.
        /// </summary>
        internal static string AliasDojoTelefono {
            get {
                return ResourceManager.GetString("AliasDojoTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ubicacion.
        /// </summary>
        internal static string AliasDojoUbicacion {
            get {
                return ResourceManager.GetString("AliasDojoUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estado.
        /// </summary>
        internal static string AliasEstado {
            get {
                return ResourceManager.GetString("AliasEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a status.
        /// </summary>
        internal static string AliasEstadoMatricula {
            get {
                return ResourceManager.GetString("AliasEstadoMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a costo.
        /// </summary>
        internal static string AliasEventoCosto {
            get {
                return ResourceManager.GetString("AliasEventoCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaInscripcion.
        /// </summary>
        internal static string AliasEventoFechaInscripcion {
            get {
                return ResourceManager.GetString("AliasEventoFechaInscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idUbicacion.
        /// </summary>
        internal static string AliasEventoHorarioId {
            get {
                return ResourceManager.GetString("AliasEventoHorarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string AliasEventoNombre {
            get {
                return ResourceManager.GetString("AliasEventoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idTipoEvento.
        /// </summary>
        internal static string AliasEventoTipoEveId {
            get {
                return ResourceManager.GetString("AliasEventoTipoEveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idUbicacion.
        /// </summary>
        internal static string AliasEventoUbicacionId {
            get {
                return ResourceManager.GetString("AliasEventoUbicacionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaFin.
        /// </summary>
        internal static string AliasFechaFinHorario {
            get {
                return ResourceManager.GetString("AliasFechaFinHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaInicio.
        /// </summary>
        internal static string AliasFechaInicioHorario {
            get {
                return ResourceManager.GetString("AliasFechaInicioHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fecha.
        /// </summary>
        internal static string AliasFechaPago {
            get {
                return ResourceManager.GetString("AliasFechaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaPag.
        /// </summary>
        internal static string AliasFechaPagoMatricula {
            get {
                return ResourceManager.GetString("AliasFechaPagoMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaUltimoPago.
        /// </summary>
        internal static string AliasFechaUltimoPagoMatricula {
            get {
                return ResourceManager.GetString("AliasFechaUltimoPagoMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a forma.
        /// </summary>
        internal static string AliasFormaPago {
            get {
                return ResourceManager.GetString("AliasFormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a horaFin.
        /// </summary>
        internal static string AliasHoraFinHorario {
            get {
                return ResourceManager.GetString("AliasHoraFinHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a horaInicio.
        /// </summary>
        internal static string AliasHoraInicioHorario {
            get {
                return ResourceManager.GetString("AliasHoraInicioHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasHorarioEventoId {
            get {
                return ResourceManager.GetString("AliasHorarioEventoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasIdCinta {
            get {
                return ResourceManager.GetString("AliasIdCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasIdCompetencia {
            get {
                return ResourceManager.GetString("AliasIdCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a identificador.
        /// </summary>
        internal static string AliasIdentificadorMatricula {
            get {
                return ResourceManager.GetString("AliasIdentificadorMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasIdEvento {
            get {
                return ResourceManager.GetString("AliasIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasIdHorario {
            get {
                return ResourceManager.GetString("AliasIdHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasIdMatricula {
            get {
                return ResourceManager.GetString("AliasIdMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasIdTipoEvento {
            get {
                return ResourceManager.GetString("AliasIdTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasIdUbicacion {
            get {
                return ResourceManager.GetString("AliasIdUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fecha.
        /// </summary>
        internal static string AliasInscripcionFecha {
            get {
                return ResourceManager.GetString("AliasInscripcionFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fecha.
        /// </summary>
        internal static string AliasInscripcionFechaCompetencia {
            get {
                return ResourceManager.GetString("AliasInscripcionFechaCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a monto.
        /// </summary>
        internal static string AliasMontoEvento {
            get {
                return ResourceManager.GetString("AliasMontoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pago.
        /// </summary>
        internal static string AliasMontoMatricula {
            get {
                return ResourceManager.GetString("AliasMontoMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a direccion.
        /// </summary>
        internal static string AliasOrganizacionDireccion {
            get {
                return ResourceManager.GetString("AliasOrganizacionDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a email.
        /// </summary>
        internal static string AliasOrganizacionEmail {
            get {
                return ResourceManager.GetString("AliasOrganizacionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasOrganizacionId {
            get {
                return ResourceManager.GetString("AliasOrganizacionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string AliasOrganizacionNombre {
            get {
                return ResourceManager.GetString("AliasOrganizacionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a telefono.
        /// </summary>
        internal static string AliasOrganizacionTelefono {
            get {
                return ResourceManager.GetString("AliasOrganizacionTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a apellido.
        /// </summary>
        internal static string AliasPersonaApellido {
            get {
                return ResourceManager.GetString("AliasPersonaApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a direccion.
        /// </summary>
        internal static string AliasPersonaDireccion {
            get {
                return ResourceManager.GetString("AliasPersonaDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a idDojo.
        /// </summary>
        internal static string AliasPersonaDojoId {
            get {
                return ResourceManager.GetString("AliasPersonaDojoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fechaNacimiento.
        /// </summary>
        internal static string AliasPersonaFechaNacimiento {
            get {
                return ResourceManager.GetString("AliasPersonaFechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string AliasPersonaNombre {
            get {
                return ResourceManager.GetString("AliasPersonaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasTipoEveEventoId {
            get {
                return ResourceManager.GetString("AliasTipoEveEventoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string AliasTipoEvento {
            get {
                return ResourceManager.GetString("AliasTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nombre.
        /// </summary>
        internal static string AliasTipoEventoNombre {
            get {
                return ResourceManager.GetString("AliasTipoEventoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a id.
        /// </summary>
        internal static string AliasUbicacionId {
            get {
                return ResourceManager.GetString("AliasUbicacionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SKD_00_007.
        /// </summary>
        internal static string Codigo_Numero_Parametro_Invalido {
            get {
                return ResourceManager.GetString("Codigo_Numero_Parametro_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaDojo.
        /// </summary>
        internal static string ConsultaDojoXId {
            get {
                return ResourceManager.GetString("ConsultaDojoXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaOrganizacion.
        /// </summary>
        internal static string ConsultaOrganizacionXId {
            get {
                return ResourceManager.GetString("ConsultaOrganizacionXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaPersona.
        /// </summary>
        internal static string ConsultaPersonaXId {
            get {
                return ResourceManager.GetString("ConsultaPersonaXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarCintas.
        /// </summary>
        internal static string ConsultarCintas {
            get {
                return ResourceManager.GetString("ConsultarCintas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaCinta.
        /// </summary>
        internal static string ConsultarCintaXId {
            get {
                return ResourceManager.GetString("ConsultarCintaXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarCompetenciasAsistidas.
        /// </summary>
        internal static string ConsultarCompetenciasAsistidas {
            get {
                return ResourceManager.GetString("ConsultarCompetenciasAsistidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaCompetenciaInscrita.
        /// </summary>
        internal static string ConsultarCompetenciasInscritas {
            get {
                return ResourceManager.GetString("ConsultarCompetenciasInscritas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaCompetencia.
        /// </summary>
        internal static string ConsultarCompetenciaXId {
            get {
                return ResourceManager.GetString("ConsultarCompetenciaXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarEstadoMatricula.
        /// </summary>
        internal static string ConsultarEstadoMatricula {
            get {
                return ResourceManager.GetString("ConsultarEstadoMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarEventosAsistidos.
        /// </summary>
        internal static string ConsultarEventosAsistidos {
            get {
                return ResourceManager.GetString("ConsultarEventosAsistidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaEventoInscrito.
        /// </summary>
        internal static string ConsultarEventosInscritos {
            get {
                return ResourceManager.GetString("ConsultarEventosInscritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarEventosPagos.
        /// </summary>
        internal static string ConsultarEventosPagos {
            get {
                return ResourceManager.GetString("ConsultarEventosPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaEvento.
        /// </summary>
        internal static string ConsultarEventoXId {
            get {
                return ResourceManager.GetString("ConsultarEventoXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarFechaCinta.
        /// </summary>
        internal static string ConsultarFechaCinta {
            get {
                return ResourceManager.GetString("ConsultarFechaCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarFechaInscripcion.
        /// </summary>
        internal static string ConsultarFechaInscripcion {
            get {
                return ResourceManager.GetString("ConsultarFechaInscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarFechaInscripcionCompetencia.
        /// </summary>
        internal static string ConsultarFechaInscripcionCompetencia {
            get {
                return ResourceManager.GetString("ConsultarFechaInscripcionCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarFechaPagoEvento.
        /// </summary>
        internal static string ConsultarFechaPagoEvento {
            get {
                return ResourceManager.GetString("ConsultarFechaPagoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarFormaPagoMatricula.
        /// </summary>
        internal static string ConsultarFormaPagoMatricula {
            get {
                return ResourceManager.GetString("ConsultarFormaPagoMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaHorarioPractica.
        /// </summary>
        internal static string ConsultarHorarioPractica {
            get {
                return ResourceManager.GetString("ConsultarHorarioPractica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarHorario.
        /// </summary>
        internal static string ConsultarHorarioXId {
            get {
                return ResourceManager.GetString("ConsultarHorarioXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarIdEvento.
        /// </summary>
        internal static string ConsultarIdEvento {
            get {
                return ResourceManager.GetString("ConsultarIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarIdMatricula.
        /// </summary>
        internal static string ConsultarIdMatricula {
            get {
                return ResourceManager.GetString("ConsultarIdMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarMatriculasPagas.
        /// </summary>
        internal static string ConsultarMatriculasPagas {
            get {
                return ResourceManager.GetString("ConsultarMatriculasPagas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarMatricula.
        /// </summary>
        internal static string ConsultarMatriculaXId {
            get {
                return ResourceManager.GetString("ConsultarMatriculaXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarMontoEvento.
        /// </summary>
        internal static string ConsultarMontoEvento {
            get {
                return ResourceManager.GetString("ConsultarMontoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarMontoMatricula.
        /// </summary>
        internal static string ConsultarMontoMatricula {
            get {
                return ResourceManager.GetString("ConsultarMontoMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaTipoEvento.
        /// </summary>
        internal static string ConsultarTipoEventoXId {
            get {
                return ResourceManager.GetString("ConsultarTipoEventoXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultarUltimaCinta.
        /// </summary>
        internal static string ConsultarUltimaCinta {
            get {
                return ResourceManager.GetString("ConsultarUltimaCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M7_ConsultaUbicacion.
        /// </summary>
        internal static string ConsultaUbicacionXId {
            get {
                return ResourceManager.GetString("ConsultaUbicacionXId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número del parametro es invalido, debe ser un entero positivo.
        /// </summary>
        internal static string Mensaje_Numero_Parametro_invalido {
            get {
                return ResourceManager.GetString("Mensaje_Numero_Parametro_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida del Método.
        /// </summary>
        internal static string MensajeFinInfoLogger {
            get {
                return ResourceManager.GetString("MensajeFinInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada en el Método.
        /// </summary>
        internal static string MensajeInicioInfoLogger {
            get {
                return ResourceManager.GetString("MensajeInicioInfoLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @cin_id.
        /// </summary>
        internal static string ParamIdCinta {
            get {
                return ResourceManager.GetString("ParamIdCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @comp_id.
        /// </summary>
        internal static string ParamIdCompetencia {
            get {
                return ResourceManager.GetString("ParamIdCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @doj_id.
        /// </summary>
        internal static string ParamIdDojo {
            get {
                return ResourceManager.GetString("ParamIdDojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @eve_id.
        /// </summary>
        internal static string ParamIdEvento {
            get {
                return ResourceManager.GetString("ParamIdEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @hor_id.
        /// </summary>
        internal static string ParamIdHorario {
            get {
                return ResourceManager.GetString("ParamIdHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @mat_id.
        /// </summary>
        internal static string ParamIdMatricula {
            get {
                return ResourceManager.GetString("ParamIdMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @org_id.
        /// </summary>
        internal static string ParamIdOrganizacion {
            get {
                return ResourceManager.GetString("ParamIdOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @per_id.
        /// </summary>
        internal static string ParamIdPersona {
            get {
                return ResourceManager.GetString("ParamIdPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idTipoEvento.
        /// </summary>
        internal static string ParamIdTipoEvento {
            get {
                return ResourceManager.GetString("ParamIdTipoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idUbicacion.
        /// </summary>
        internal static string ParamIdUbicacion {
            get {
                return ResourceManager.GetString("ParamIdUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idAtleta.
        /// </summary>
        internal static string ParamIdUsuarioLogueado {
            get {
                return ResourceManager.GetString("ParamIdUsuarioLogueado", resourceCulture);
            }
        }
    }
}
