//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interfaz_Presentadores.Modulo2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecursosInterfazPresentadorM2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosInterfazPresentadorM2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interfaz_Presentadores.Modulo2.RecursosInterfazPresentadorM2", typeof(RecursosInterfazPresentadorM2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string agregarCat {
            get {
                return ResourceManager.GetString("agregarCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&apos;Añadir&apos; class=&apos;btn btn-success glyphicon glyphicon-plus-sign botonRol&apos; data-toggle=&apos;modal&apos; data-target=&apos;#modal-create&apos; data-id=&apos;.
        /// </summary>
        public static string AgregarRolEtq {
            get {
                return ResourceManager.GetString("AgregarRolEtq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaKARAteDO2015.
        /// </summary>
        public static string claveDES {
            get {
                return ResourceManager.GetString("claveDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SKD_00_13.
        /// </summary>
        public static string Codigo_Error_AgregarRol {
            get {
                return ResourceManager.GetString("Codigo_Error_AgregarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SKD_00_14.
        /// </summary>
        public static string Codigo_Error_ConsultarRolUsuario {
            get {
                return ResourceManager.GetString("Codigo_Error_ConsultarRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SKD_00_12.
        /// </summary>
        public static string Codigo_Error_EliminarRol {
            get {
                return ResourceManager.GetString("Codigo_Error_EliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SKD_00_15.
        /// </summary>
        public static string Codigo_Error_FiltrarRol {
            get {
                return ResourceManager.GetString("Codigo_Error_FiltrarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SKD_00_10.
        /// </summary>
        public static string Codigo_Error_Hash {
            get {
                return ResourceManager.GetString("Codigo_Error_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SKD_17.
        /// </summary>
        public static string Codigo_Error_RolNoEditable {
            get {
                return ResourceManager.GetString("Codigo_Error_RolNoEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SKD_00_16.
        /// </summary>
        public static string Codigo_Error_ValidarPrioridad {
            get {
                return ResourceManager.GetString("Codigo_Error_ValidarPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string eliminarCat {
            get {
                return ResourceManager.GetString("eliminarCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&apos;Eliminar&apos; class=&apos;btn btn-danger glyphicon glyphicon-remove-sign botonRol&apos; data-toggle=&apos;modal&apos; data-target=&apos;#modal-delete&apos; data-id=&apos;.
        /// </summary>
        public static string EliminarRolEtq {
            get {
                return ResourceManager.GetString("EliminarRolEtq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a x2.
        /// </summary>
        public static string equis2 {
            get {
                return ResourceManager.GetString("equis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;asp:DropDownList id=&quot;RolList&quot; class=&quot;btn btn-default dropdown-toggle&quot; AutoPostBack=&quot;True&quot; OnSelectedIndexChanged=&quot;Selection_Change&quot; runat=&quot;server&quot;&gt;.
        /// </summary>
        public static string etiquetaAperturaDropDawn {
            get {
                return ResourceManager.GetString("etiquetaAperturaDropDawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/asp:DropDownList&gt;.
        /// </summary>
        public static string etiquetaCierreDropDawn {
            get {
                return ResourceManager.GetString("etiquetaCierreDropDawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../../dist/img/AvatarSKD.jpg.
        /// </summary>
        public static string imgDefault {
            get {
                return ResourceManager.GetString("imgDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info.
        /// </summary>
        public static string informacionCat {
            get {
                return ResourceManager.GetString("informacionCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a title=&apos;Info&apos; class=&apos;btn btn-info glyphicon glyphicon-info-sign &apos;data-toggle=&apos;modal&apos;  data-target=&apos;#modal-info&apos; data-id=&apos;.
        /// </summary>
        public static string InfoRol {
            get {
                return ResourceManager.GetString("InfoRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al agregar rol.
        /// </summary>
        public static string Mensaje_Error_AgregarRol {
            get {
                return ResourceManager.GetString("Mensaje_Error_AgregarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al consultar rol de usuario.
        /// </summary>
        public static string Mensaje_Error_ConsultarRolUsuario {
            get {
                return ResourceManager.GetString("Mensaje_Error_ConsultarRolUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar rol .
        /// </summary>
        public static string Mensaje_Error_EliminarRol {
            get {
                return ResourceManager.GetString("Mensaje_Error_EliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al filtrar rol.
        /// </summary>
        public static string Mensaje_Error_FiltarRol {
            get {
                return ResourceManager.GetString("Mensaje_Error_FiltarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error encontrado en login.hash.
        /// </summary>
        public static string Mensaje_Error_Hash {
            get {
                return ResourceManager.GetString("Mensaje_Error_Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error rol no editable.
        /// </summary>
        public static string Mensaje_Error_RolNoEditable {
            get {
                return ResourceManager.GetString("Mensaje_Error_RolNoEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol no registrado/validado en sistema: LogicaNegociosSKD.logicaRol.prioridadRol().
        /// </summary>
        public static string Mensaje_Error_RolSinRegistro {
            get {
                return ResourceManager.GetString("Mensaje_Error_RolSinRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al validar prioridad.
        /// </summary>
        public static string Mensaje_Error_ValidarPrioridad {
            get {
                return ResourceManager.GetString("Mensaje_Error_ValidarPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a user.
        /// </summary>
        public static string parametroIDUsuario {
            get {
                return ResourceManager.GetString("parametroIDUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos; href=&apos;#&apos;&gt;&lt;/a&gt;.
        /// </summary>
        public static string RolFinEtq {
            get {
                return ResourceManager.GetString("RolFinEtq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +.
        /// </summary>
        public static string signoMas {
            get {
                return ResourceManager.GetString("signoMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;asp:ListItem Value=&quot;.
        /// </summary>
        public static string subEtiquetaApertura {
            get {
                return ResourceManager.GetString("subEtiquetaApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;.
        /// </summary>
        public static string subEtiquetaCierreApertura {
            get {
                return ResourceManager.GetString("subEtiquetaCierreApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/asp:ListItem&gt;.
        /// </summary>
        public static string subEtiquetaCierreTotal {
            get {
                return ResourceManager.GetString("subEtiquetaCierreTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;asp:ListItem Selected=&quot;True&quot; Value=&quot;select&quot;&gt;-Seleccionar rol- &lt;/asp:ListItem&gt;.
        /// </summary>
        public static string subEtiquetaSeleccionar {
            get {
                return ResourceManager.GetString("subEtiquetaSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/td&gt;.
        /// </summary>
        public static string tdFin {
            get {
                return ResourceManager.GetString("tdFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td&gt;.
        /// </summary>
        public static string tdIni {
            get {
                return ResourceManager.GetString("tdIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/tr&gt;.
        /// </summary>
        public static string trFin {
            get {
                return ResourceManager.GetString("trFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr style=&apos;background: rgb(224, 235, 235);&apos;&gt;.
        /// </summary>
        public static string trInfoIni {
            get {
                return ResourceManager.GetString("trInfoIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr&gt;.
        /// </summary>
        public static string trIni {
            get {
                return ResourceManager.GetString("trIni", resourceCulture);
            }
        }
    }
}
