//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.Modulo13 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo13 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo13() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.Modulo13.RecursosBDModulo13", typeof(RecursosBDModulo13).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per_apellido.
        /// </summary>
        internal static string apellido {
            get {
                return ResourceManager.GetString("apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinta.
        /// </summary>
        internal static string Cinta {
            get {
                return ResourceManager.GetString("Cinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_ConsultarAtletasCintas.
        /// </summary>
        internal static string ConsultarAtleta {
            get {
                return ResourceManager.GetString("ConsultarAtleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13_ListarMorosos.
        /// </summary>
        internal static string ConsultarListaMorosidad {
            get {
                return ResourceManager.GetString("ConsultarListaMorosidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per_num_doc_id.
        /// </summary>
        internal static string dni {
            get {
                return ResourceManager.GetString("dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doj_nombre.
        /// </summary>
        internal static string DojoNombre {
            get {
                return ResourceManager.GetString("DojoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per_fecha_nacimiento.
        /// </summary>
        internal static string Edad {
            get {
                return ResourceManager.GetString("Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per_estatura.
        /// </summary>
        internal static string estatura {
            get {
                return ResourceManager.GetString("estatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @cin_id.
        /// </summary>
        internal static string idCinta {
            get {
                return ResourceManager.GetString("idCinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ev_id.
        /// </summary>
        internal static string idEvento {
            get {
                return ResourceManager.GetString("idEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meseMoroso.
        /// </summary>
        internal static string meseMoroso {
            get {
                return ResourceManager.GetString("meseMoroso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monto.
        /// </summary>
        internal static string MontoTotal {
            get {
                return ResourceManager.GetString("MontoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per_nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to persona.
        /// </summary>
        internal static string ParamIdPersona {
            get {
                return ResourceManager.GetString("ParamIdPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to persona_id.
        /// </summary>
        internal static string per_id {
            get {
                return ResourceManager.GetString("per_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per_peso.
        /// </summary>
        internal static string peso {
            get {
                return ResourceManager.GetString("peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per_sexo.
        /// </summary>
        internal static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
    }
}
