//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSKD.Modulo12 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosBDModulo12 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosBDModulo12() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatosSKD.Modulo12.RecursosBDModulo12", typeof(RecursosBDModulo12).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idCompetencia.
        /// </summary>
        internal static string AliasIdCompetencia {
            get {
                return ResourceManager.GetString("AliasIdCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idOrganizacion.
        /// </summary>
        internal static string AliasIdOrganizacion {
            get {
                return ResourceManager.GetString("AliasIdOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idUbicacion.
        /// </summary>
        internal static string AliasIdUbicacion {
            get {
                return ResourceManager.GetString("AliasIdUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreCiudad.
        /// </summary>
        internal static string AliasNombreCiudad {
            get {
                return ResourceManager.GetString("AliasNombreCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreCompetencia.
        /// </summary>
        internal static string AliasNombreCompetencia {
            get {
                return ResourceManager.GetString("AliasNombreCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreEstado.
        /// </summary>
        internal static string AliasNombreEstado {
            get {
                return ResourceManager.GetString("AliasNombreEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombreOrganizacion.
        /// </summary>
        internal static string AliasNombreOrganizacion {
            get {
                return ResourceManager.GetString("AliasNombreOrganizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusCompetencia.
        /// </summary>
        internal static string AliasStatusCompetencia {
            get {
                return ResourceManager.GetString("AliasStatusCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tipoCompetencia.
        /// </summary>
        internal static string AliasTipoCompetencia {
            get {
                return ResourceManager.GetString("AliasTipoCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to todasOrganizaciones.
        /// </summary>
        internal static string AliasTodasOrganizaciones {
            get {
                return ResourceManager.GetString("AliasTodasOrganizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M12_ConsultarCompetencias.
        /// </summary>
        internal static string ConsultarCompetencias {
            get {
                return ResourceManager.GetString("ConsultarCompetencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas.
        /// </summary>
        internal static string TodasLasOrganizaciones {
            get {
                return ResourceManager.GetString("TodasLasOrganizaciones", resourceCulture);
            }
        }
    }
}
