//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace templateApp.GUI.Modulo16 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M16_Recursointerfaz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M16_Recursointerfaz() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("templateApp.GUI.Modulo16.M16_Recursointerfaz", typeof(M16_Recursointerfaz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td&gt;.
        /// </summary>
        internal static string ABRIR_TD {
            get {
                return ResourceManager.GetString("ABRIR_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr id=.
        /// </summary>
        internal static string ABRIR_TR {
            get {
                return ResourceManager.GetString("ABRIR_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr id=E-.
        /// </summary>
        internal static string ABRIR_TR_EVENTO {
            get {
                return ResourceManager.GetString("ABRIR_TR_EVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr id=I-.
        /// </summary>
        internal static string ABRIR_TR_INVENTARIO {
            get {
                return ResourceManager.GetString("ABRIR_TR_INVENTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr id=M-.
        /// </summary>
        internal static string ABRIR_TR_MATRICULA {
            get {
                return ResourceManager.GetString("ABRIR_TR_MATRICULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;M16_ConsultarMensualidad.aspx?compAgregar=.
        /// </summary>
        internal static string BOTON_AGREGAR_CARRITO {
            get {
                return ResourceManager.GetString("BOTON_AGREGAR_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BOTON_CERRAR {
            get {
                return ResourceManager.GetString("BOTON_CERRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-danger glyphicon glyphicon-remove-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;M12_ListarCompetencias.aspx?compEliminar=.
        /// </summary>
        internal static string BOTON_ELIMINAR {
            get {
                return ResourceManager.GetString("BOTON_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info&quot; href=&quot;M12_ListarCompetencias.aspx?compDetalle=.
        /// </summary>
        internal static string BOTON_INFO {
            get {
                return ResourceManager.GetString("BOTON_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info1&quot; href=&quot;M16_ConsultarProducto.aspx?impDetalle=.
        /// </summary>
        internal static string BOTON_INFO_EVENTO {
            get {
                return ResourceManager.GetString("BOTON_INFO_EVENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-primary glyphicon glyphicon-info-sign&quot; data-toggle=&quot;modal&quot; data-target=&quot;#modal-info1&quot; href=&quot;M16_ConsultarProducto.aspx?impDetalle=.
        /// </summary>
        internal static string BOTON_INFO_PRODUCTO {
            get {
                return ResourceManager.GetString("BOTON_INFO_PRODUCTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;a class=&quot;btn btn-default glyphicon glyphicon-pencil&quot; href=&quot;M12_ModificarCompetencias.aspx?compMod=.
        /// </summary>
        internal static string BOTON_MODIFICAR {
            get {
                return ResourceManager.GetString("BOTON_MODIFICAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/td&gt;.
        /// </summary>
        internal static string CERRAR_TD {
            get {
                return ResourceManager.GetString("CERRAR_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/tr&gt;.
        /// </summary>
        internal static string CERRAR_TR {
            get {
                return ResourceManager.GetString("CERRAR_TR", resourceCulture);
            }
        }
    }
}
